// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Specifies options for controlling advanced machine features.
public struct AdvancedMachineFeatures: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Whether to enable nested virtualization or not (default is
  /// false).
  public var enableNestedVirtualization: Swift.Bool? = nil

  /// Optional. The number of threads per physical core. To disable simultaneous
  /// multithreading (SMT) set this to 1. If unset, the maximum number
  /// of threads supported per core by the underlying processor is
  /// assumed.
  public var threadsPerCore: Swift.Int32? = nil

  /// Optional. The number of physical cores to expose to an instance. Multiply
  /// by the number of threads per core to compute the total number of virtual
  /// CPUs to expose to the instance. If unset, the number of cores is
  /// inferred from the instance's nominal CPU count and the underlying
  /// platform's SMT width.
  public var visibleCoreCount: Swift.Int32? = nil

  /// Optional. Whether to enable UEFI networking for instance creation.
  public var enableUefiNetworking: Swift.Bool? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AdvancedMachineFeatures`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AdvancedMachineFeatures().with { $0.enableNestedVirtualization = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enableNestedVirtualization = CodingKeys(stringValue: "enableNestedVirtualization")
    static let threadsPerCore = CodingKeys(stringValue: "threadsPerCore")
    static let visibleCoreCount = CodingKeys(stringValue: "visibleCoreCount")
    static let enableUefiNetworking = CodingKeys(stringValue: "enableUefiNetworking")

    static let _knownKeys: Set<Swift.String> = [
      "enableNestedVirtualization",
      "threadsPerCore",
      "visibleCoreCount",
      "enableUefiNetworking",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.enableNestedVirtualization = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableNestedVirtualization)
    self.threadsPerCore = try container.decodeIfPresent(Swift.Int32.self, forKey: .threadsPerCore)
    self.visibleCoreCount = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .visibleCoreCount)
    self.enableUefiNetworking = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableUefiNetworking)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(
      self.enableNestedVirtualization, forKey: .enableNestedVirtualization)
    try container.encodeIfPresent(self.threadsPerCore, forKey: .threadsPerCore)
    try container.encodeIfPresent(self.visibleCoreCount, forKey: .visibleCoreCount)
    try container.encodeIfPresent(self.enableUefiNetworking, forKey: .enableUefiNetworking)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `AdvancedMachineFeatures`: `"type.googleapis.com/google.cloud.backupdr.v1.AdvancedMachineFeatures"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.AdvancedMachineFeatures"
  }

  /// Initialize an instance of `AdvancedMachineFeatures` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.AdvancedMachineFeatures"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AdvancedMachineFeatures` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
