// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// AlloyDbClusterBackupProperties represents AlloyDB cluster
/// backup properties.
/// .
public struct AlloyDbClusterBackupProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// An optional text description for the backup.
  public var description: Swift.String? = nil

  /// Output only. Storage usage of this particular backup
  public var storedBytes: Swift.Int64 = Swift.Int64()

  /// Output only. The chain id of this backup. Backups belonging to the same
  /// chain are sharing the same chain id. This property is calculated and
  /// maintained by BackupDR.
  public var chainId: Swift.String = Swift.String()

  /// Output only. The PostgreSQL major version of the AlloyDB cluster when the
  /// backup was taken.
  public var databaseVersion: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AlloyDbClusterBackupProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AlloyDbClusterBackupProperties().with { $0.description = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let description = CodingKeys(stringValue: "description")
    static let storedBytes = CodingKeys(stringValue: "storedBytes")
    static let chainId = CodingKeys(stringValue: "chainId")
    static let databaseVersion = CodingKeys(stringValue: "databaseVersion")

    static let _knownKeys: Set<Swift.String> = [
      "description",
      "storedBytes",
      "chainId",
      "databaseVersion",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .storedBytes) {
      self.storedBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .chainId) {
      self.chainId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .databaseVersion) {
      self.databaseVersion = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.description, forKey: .description)
    try container.encode(self.storedBytes, forKey: .storedBytes)
    try container.encode(self.chainId, forKey: .chainId)
    try container.encode(self.databaseVersion, forKey: .databaseVersion)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `AlloyDbClusterBackupProperties`: `"type.googleapis.com/google.cloud.backupdr.v1.AlloyDbClusterBackupProperties"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.AlloyDbClusterBackupProperties"
  }

  /// Initialize an instance of `AlloyDbClusterBackupProperties` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.AlloyDbClusterBackupProperties"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AlloyDbClusterBackupProperties` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
