// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An instance-attached disk resource.
public struct AttachedDisk: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Specifies the parameters to initialize this disk.
  public var initializeParams: AttachedDisk.InitializeParams? = nil

  /// Optional. This is used as an identifier for the disks. This is the unique
  /// name has to provided to modify disk parameters like disk_name and
  /// replica_zones (in case of RePDs)
  public var deviceName: Swift.String? = nil

  /// Optional. Type of the resource.
  public var kind: Swift.String? = nil

  /// Specifies the type of the disk.
  @available(*, deprecated)
  public var diskTypeDeprecated: AttachedDisk.DiskType? = nil

  /// Optional. The mode in which to attach this disk.
  public var mode: AttachedDisk.DiskMode? = nil

  /// Optional. Specifies a valid partial or full URL to an existing Persistent
  /// Disk resource.
  public var source: Swift.String? = nil

  /// Optional. A zero-based index to this disk, where 0 is reserved for the
  /// boot disk.
  public var index: Swift.Int64? = nil

  /// Optional. Indicates that this is a boot disk. The virtual machine will use
  /// the first partition of the disk for its root filesystem.
  public var boot: Swift.Bool? = nil

  /// Optional. Specifies whether the disk will be auto-deleted when the instance
  /// is deleted (but not when the disk is detached from the instance).
  public var autoDelete: Swift.Bool? = nil

  /// Optional. Any valid publicly visible licenses.
  public var license: [Swift.String] = []

  /// Optional. Specifies the disk interface to use for attaching this disk.
  public var diskInterface: AttachedDisk.DiskInterface? = nil

  /// Optional. A list of features to enable on the guest operating system.
  /// Applicable only for bootable images.
  public var guestOsFeature: [GuestOsFeature] = []

  /// Optional. Encrypts or decrypts a disk using a customer-supplied
  /// encryption key.
  public var diskEncryptionKey: CustomerEncryptionKey? = nil

  /// Optional. The size of the disk in GB.
  public var diskSizeGb: Swift.Int64? = nil

  /// Optional. Output only. The state of the disk.
  public var savedState: AttachedDisk.DiskSavedState? = nil

  /// Optional. Output only. The URI of the disk type resource. For example:
  /// projects/project/zones/zone/diskTypes/pd-standard or pd-ssd
  public var diskType: Swift.String? = nil

  /// Optional. Specifies the type of the disk.
  public var type: AttachedDisk.DiskType? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AttachedDisk`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AttachedDisk().with { $0.initializeParams = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let initializeParams = CodingKeys(stringValue: "initializeParams")
    static let deviceName = CodingKeys(stringValue: "deviceName")
    static let kind = CodingKeys(stringValue: "kind")
    static let diskTypeDeprecated = CodingKeys(stringValue: "diskTypeDeprecated")
    static let mode = CodingKeys(stringValue: "mode")
    static let source = CodingKeys(stringValue: "source")
    static let index = CodingKeys(stringValue: "index")
    static let boot = CodingKeys(stringValue: "boot")
    static let autoDelete = CodingKeys(stringValue: "autoDelete")
    static let license = CodingKeys(stringValue: "license")
    static let diskInterface = CodingKeys(stringValue: "diskInterface")
    static let guestOsFeature = CodingKeys(stringValue: "guestOsFeature")
    static let diskEncryptionKey = CodingKeys(stringValue: "diskEncryptionKey")
    static let diskSizeGb = CodingKeys(stringValue: "diskSizeGb")
    static let savedState = CodingKeys(stringValue: "savedState")
    static let diskType = CodingKeys(stringValue: "diskType")
    static let type = CodingKeys(stringValue: "type")

    static let _knownKeys: Set<Swift.String> = [
      "initializeParams",
      "deviceName",
      "kind",
      "diskTypeDeprecated",
      "mode",
      "source",
      "index",
      "boot",
      "autoDelete",
      "license",
      "diskInterface",
      "guestOsFeature",
      "diskEncryptionKey",
      "diskSizeGb",
      "savedState",
      "diskType",
      "type",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.initializeParams = try container.decodeIfPresent(
      AttachedDisk.InitializeParams.self, forKey: .initializeParams)
    self.deviceName = try container.decodeIfPresent(Swift.String.self, forKey: .deviceName)
    self.kind = try container.decodeIfPresent(Swift.String.self, forKey: .kind)
    self.diskTypeDeprecated = try container.decodeIfPresent(
      AttachedDisk.DiskType.self, forKey: .diskTypeDeprecated)
    self.mode = try container.decodeIfPresent(AttachedDisk.DiskMode.self, forKey: .mode)
    self.source = try container.decodeIfPresent(Swift.String.self, forKey: .source)
    self.index = try container.decodeIfPresent(Swift.Int64.self, forKey: .index)
    self.boot = try container.decodeIfPresent(Swift.Bool.self, forKey: .boot)
    self.autoDelete = try container.decodeIfPresent(Swift.Bool.self, forKey: .autoDelete)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .license) {
      self.license = value
    }
    self.diskInterface = try container.decodeIfPresent(
      AttachedDisk.DiskInterface.self, forKey: .diskInterface)
    if let value = try container.decodeIfPresent([GuestOsFeature].self, forKey: .guestOsFeature) {
      self.guestOsFeature = value
    }
    self.diskEncryptionKey = try container.decodeIfPresent(
      CustomerEncryptionKey.self, forKey: .diskEncryptionKey)
    self.diskSizeGb = try container.decodeIfPresent(Swift.Int64.self, forKey: .diskSizeGb)
    self.savedState = try container.decodeIfPresent(
      AttachedDisk.DiskSavedState.self, forKey: .savedState)
    self.diskType = try container.decodeIfPresent(Swift.String.self, forKey: .diskType)
    self.type = try container.decodeIfPresent(AttachedDisk.DiskType.self, forKey: .type)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.initializeParams, forKey: .initializeParams)
    try container.encodeIfPresent(self.deviceName, forKey: .deviceName)
    try container.encodeIfPresent(self.kind, forKey: .kind)
    try container.encodeIfPresent(self.diskTypeDeprecated, forKey: .diskTypeDeprecated)
    try container.encodeIfPresent(self.mode, forKey: .mode)
    try container.encodeIfPresent(self.source, forKey: .source)
    try container.encodeIfPresent(self.index, forKey: .index)
    try container.encodeIfPresent(self.boot, forKey: .boot)
    try container.encodeIfPresent(self.autoDelete, forKey: .autoDelete)
    try container.encode(self.license, forKey: .license)
    try container.encodeIfPresent(self.diskInterface, forKey: .diskInterface)
    try container.encode(self.guestOsFeature, forKey: .guestOsFeature)
    try container.encodeIfPresent(self.diskEncryptionKey, forKey: .diskEncryptionKey)
    try container.encodeIfPresent(self.diskSizeGb, forKey: .diskSizeGb)
    try container.encodeIfPresent(self.savedState, forKey: .savedState)
    try container.encodeIfPresent(self.diskType, forKey: .diskType)
    try container.encodeIfPresent(self.type, forKey: .type)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Specifies the parameters to initialize this disk.
  public struct InitializeParams: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Specifies the disk name. If not specified, the default is to
    /// use the name of the instance.
    public var diskName: Swift.String? = nil

    /// Optional. URL of the zone where the disk should be created.
    /// Required for each regional disk associated with the instance.
    public var replicaZones: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InitializeParams`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InitializeParams().with { $0.diskName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let diskName = CodingKeys(stringValue: "diskName")
      static let replicaZones = CodingKeys(stringValue: "replicaZones")

      static let _knownKeys: Set<Swift.String> = [
        "diskName",
        "replicaZones",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.diskName = try container.decodeIfPresent(Swift.String.self, forKey: .diskName)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .replicaZones) {
        self.replicaZones = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.diskName, forKey: .diskName)
      try container.encode(self.replicaZones, forKey: .replicaZones)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.backupdr.v1.AttachedDisk.InitializeParams"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// List of the Disk Types.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DiskType: Codable, Equatable, Hashable, Sendable {
    /// Default value, which is unused.
    case unspecified
    /// A scratch disk type.
    case scratch
    /// A persistent disk type.
    case persistent
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .scratch: return 1
      case .persistent: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DISK_TYPE_UNSPECIFIED"
      case .scratch: return "SCRATCH"
      case .persistent: return "PERSISTENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DiskType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DISK_TYPE_UNSPECIFIED": self = .unspecified
      case "SCRATCH": self = .scratch
      case "PERSISTENT": self = .persistent
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DiskType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .scratch
      case 2: self = .persistent
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DISK_TYPE_UNSPECIFIED")
      case .scratch: return try container.encode("SCRATCH")
      case .persistent: return try container.encode("PERSISTENT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// List of the Disk Modes.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DiskMode: Codable, Equatable, Hashable, Sendable {
    /// Default value, which is unused.
    case unspecified
    /// Attaches this disk in read-write mode. Only one
    /// virtual machine at a time can be attached to a disk in read-write mode.
    case readWrite
    /// Attaches this disk in read-only mode. Multiple virtual machines can use
    /// a disk in read-only mode at a time.
    case readOnly
    /// The disk is locked for administrative reasons. Nobody else
    /// can use the disk. This mode is used (for example) when taking
    /// a snapshot of a disk to prevent mounting the disk while it is
    /// being snapshotted.
    case locked
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .readWrite: return 1
      case .readOnly: return 2
      case .locked: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DISK_MODE_UNSPECIFIED"
      case .readWrite: return "READ_WRITE"
      case .readOnly: return "READ_ONLY"
      case .locked: return "LOCKED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DiskMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DISK_MODE_UNSPECIFIED": self = .unspecified
      case "READ_WRITE": self = .readWrite
      case "READ_ONLY": self = .readOnly
      case "LOCKED": self = .locked
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DiskMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .readWrite
      case 2: self = .readOnly
      case 3: self = .locked
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DISK_MODE_UNSPECIFIED")
      case .readWrite: return try container.encode("READ_WRITE")
      case .readOnly: return try container.encode("READ_ONLY")
      case .locked: return try container.encode("LOCKED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// List of the Disk Interfaces.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DiskInterface: Codable, Equatable, Hashable, Sendable {
    /// Default value, which is unused.
    case unspecified
    /// SCSI Disk Interface.
    case scsi
    /// NVME Disk Interface.
    case nvme
    /// NVDIMM Disk Interface.
    case nvdimm
    /// ISCSI Disk Interface.
    case iscsi
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .scsi: return 1
      case .nvme: return 2
      case .nvdimm: return 3
      case .iscsi: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DISK_INTERFACE_UNSPECIFIED"
      case .scsi: return "SCSI"
      case .nvme: return "NVME"
      case .nvdimm: return "NVDIMM"
      case .iscsi: return "ISCSI"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DiskInterface/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DISK_INTERFACE_UNSPECIFIED": self = .unspecified
      case "SCSI": self = .scsi
      case "NVME": self = .nvme
      case "NVDIMM": self = .nvdimm
      case "ISCSI": self = .iscsi
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DiskInterface/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .scsi
      case 2: self = .nvme
      case 3: self = .nvdimm
      case 4: self = .iscsi
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DISK_INTERFACE_UNSPECIFIED")
      case .scsi: return try container.encode("SCSI")
      case .nvme: return try container.encode("NVME")
      case .nvdimm: return try container.encode("NVDIMM")
      case .iscsi: return try container.encode("ISCSI")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// List of the states of the Disk.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DiskSavedState: Codable, Equatable, Hashable, Sendable {
    /// Default Disk state has not been preserved.
    case unspecified
    /// Disk state has been preserved.
    case preserved
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .preserved: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DISK_SAVED_STATE_UNSPECIFIED"
      case .preserved: return "PRESERVED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DiskSavedState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DISK_SAVED_STATE_UNSPECIFIED": self = .unspecified
      case "PRESERVED": self = .preserved
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DiskSavedState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .preserved
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DISK_SAVED_STATE_UNSPECIFIED")
      case .preserved: return try container.encode("PRESERVED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.AttachedDisk"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
