// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing a BackupVault object.
public struct BackupVault: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. Name of the backup vault to create. It must have
  /// the
  /// format`"projects/{project}/locations/{location}/backupVaults/{backupvault}"`.
  /// `{backupvault}` cannot be changed after creation. It must be between 3-63
  /// characters long and must be unique within the project and location.
  public var name: Swift.String = Swift.String()

  /// Optional. The description of the BackupVault instance (2048 characters or
  /// less).
  public var description: Swift.String? = nil

  /// Optional. Resource labels to represent user provided metadata.
  /// No labels currently defined:
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The time when the instance was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the instance was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Required. The default and minimum enforced retention for each backup within
  /// the backup vault.  The enforced retention for each backup can be extended.
  public var backupMinimumEnforcedRetentionDuration: GoogleWKT.WKTDuration? = nil

  /// Optional. Setting for how a backup's enforced retention end time is
  /// inherited.
  public var backupRetentionInheritance: BackupVault.BackupRetentionInheritance? = nil

  /// Output only. Set to true when there are no backups nested under this
  /// resource.
  public var deletable: Swift.Bool? = nil

  /// Optional. Server specified ETag for the backup vault resource to
  /// prevent simultaneous updates from overwiting each other.
  public var etag: Swift.String? = nil

  /// Output only. The BackupVault resource instance state.
  public var state: BackupVault.State = BackupVault.State()

  /// Optional. Time after which the BackupVault resource is locked.
  public var effectiveTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The number of backups in this backup vault.
  public var backupCount: Swift.Int64 = Swift.Int64()

  /// Output only. Service account used by the BackupVault Service for this
  /// BackupVault.  The user should grant this account permissions in their
  /// workload project to enable the service to run backups and restores there.
  public var serviceAccount: Swift.String = Swift.String()

  /// Output only. Total size of the storage used by all backup resources.
  public var totalStoredBytes: Swift.Int64 = Swift.Int64()

  /// Output only. Immutable after resource creation until resource deletion.
  public var uid: Swift.String = Swift.String()

  /// Optional. User annotations. See https://google.aip.dev/128#annotations
  /// Stores small amounts of arbitrary data.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. Restricts access to certain sources and destinations for data
  /// being sent into, or restored from, the backup vault.
  /// Defaults to WITHIN_ORGANIZATION if not provided during creation.
  public var accessRestriction: BackupVault.AccessRestriction = BackupVault.AccessRestriction()

  /// Optional. The encryption config of the backup vault.
  public var encryptionConfig: BackupVault.EncryptionConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupVault`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupVault().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let labels = CodingKeys(stringValue: "labels")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let backupMinimumEnforcedRetentionDuration = CodingKeys(
      stringValue: "backupMinimumEnforcedRetentionDuration")
    static let backupRetentionInheritance = CodingKeys(stringValue: "backupRetentionInheritance")
    static let deletable = CodingKeys(stringValue: "deletable")
    static let etag = CodingKeys(stringValue: "etag")
    static let state = CodingKeys(stringValue: "state")
    static let effectiveTime = CodingKeys(stringValue: "effectiveTime")
    static let backupCount = CodingKeys(stringValue: "backupCount")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let totalStoredBytes = CodingKeys(stringValue: "totalStoredBytes")
    static let uid = CodingKeys(stringValue: "uid")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let accessRestriction = CodingKeys(stringValue: "accessRestriction")
    static let encryptionConfig = CodingKeys(stringValue: "encryptionConfig")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "labels",
      "createTime",
      "updateTime",
      "backupMinimumEnforcedRetentionDuration",
      "backupRetentionInheritance",
      "deletable",
      "etag",
      "state",
      "effectiveTime",
      "backupCount",
      "serviceAccount",
      "totalStoredBytes",
      "uid",
      "annotations",
      "accessRestriction",
      "encryptionConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.backupMinimumEnforcedRetentionDuration = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .backupMinimumEnforcedRetentionDuration)
    self.backupRetentionInheritance = try container.decodeIfPresent(
      BackupVault.BackupRetentionInheritance.self, forKey: .backupRetentionInheritance)
    self.deletable = try container.decodeIfPresent(Swift.Bool.self, forKey: .deletable)
    self.etag = try container.decodeIfPresent(Swift.String.self, forKey: .etag)
    if let value = try container.decodeIfPresent(BackupVault.State.self, forKey: .state) {
      self.state = value
    }
    self.effectiveTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .effectiveTime)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .backupCount) {
      self.backupCount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalStoredBytes) {
      self.totalStoredBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent(
      BackupVault.AccessRestriction.self, forKey: .accessRestriction)
    {
      self.accessRestriction = value
    }
    self.encryptionConfig = try container.decodeIfPresent(
      BackupVault.EncryptionConfig.self, forKey: .encryptionConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.description, forKey: .description)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(
      self.backupMinimumEnforcedRetentionDuration, forKey: .backupMinimumEnforcedRetentionDuration)
    try container.encodeIfPresent(
      self.backupRetentionInheritance, forKey: .backupRetentionInheritance)
    try container.encodeIfPresent(self.deletable, forKey: .deletable)
    try container.encodeIfPresent(self.etag, forKey: .etag)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.effectiveTime, forKey: .effectiveTime)
    try container.encode(self.backupCount, forKey: .backupCount)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.totalStoredBytes, forKey: .totalStoredBytes)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.accessRestriction, forKey: .accessRestriction)
    try container.encodeIfPresent(self.encryptionConfig, forKey: .encryptionConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Message describing the EncryptionConfig of backup vault.
  /// This determines how data within the vault is encrypted at rest.
  public struct EncryptionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The Cloud KMS key name to encrypt backups in this backup vault.
    /// Must be in the same region as the vault. Some workload backups like
    /// compute disk backups may use their inherited source key instead. Format:
    /// projects/{project}/locations/{location}/keyRings/{ring}/cryptoKeys/{key}
    public var kmsKeyName: Swift.String? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EncryptionConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EncryptionConfig().with { $0.kmsKeyName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let kmsKeyName = CodingKeys(stringValue: "kmsKeyName")

      static let _knownKeys: Set<Swift.String> = [
        "kmsKeyName"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.kmsKeyName = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKeyName)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.kmsKeyName, forKey: .kmsKeyName)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.backupdr.v1.BackupVault.EncryptionConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// How a backup's enforced retention end time is inherited.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum BackupRetentionInheritance: Codable, Equatable, Hashable, Sendable {
    /// Inheritance behavior not set. This will default to
    /// `INHERIT_VAULT_RETENTION`.
    case unspecified
    /// The enforced retention end time of a backup will be inherited from the
    /// backup vault's `backup_minimum_enforced_retention_duration` field.
    ///
    /// This is the default behavior.
    case inheritVaultRetention
    /// The enforced retention end time of a backup will always match the expire
    /// time of the backup.
    ///
    /// If this is set, the backup's enforced retention end time will be set to
    /// match the expire time during creation of the backup. When updating, the
    /// ERET and expire time must be updated together and have the same value.
    /// Invalid update requests will be rejected by the server.
    case matchBackupExpireTime
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inheritVaultRetention: return 1
      case .matchBackupExpireTime: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BACKUP_RETENTION_INHERITANCE_UNSPECIFIED"
      case .inheritVaultRetention: return "INHERIT_VAULT_RETENTION"
      case .matchBackupExpireTime: return "MATCH_BACKUP_EXPIRE_TIME"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BackupRetentionInheritance/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BACKUP_RETENTION_INHERITANCE_UNSPECIFIED": self = .unspecified
      case "INHERIT_VAULT_RETENTION": self = .inheritVaultRetention
      case "MATCH_BACKUP_EXPIRE_TIME": self = .matchBackupExpireTime
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BackupRetentionInheritance/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inheritVaultRetention
      case 2: self = .matchBackupExpireTime
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("BACKUP_RETENTION_INHERITANCE_UNSPECIFIED")
      case .inheritVaultRetention: return try container.encode("INHERIT_VAULT_RETENTION")
      case .matchBackupExpireTime: return try container.encode("MATCH_BACKUP_EXPIRE_TIME")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Holds the state of the backup vault resource.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// State not set.
    case unspecified
    /// The backup vault is being created.
    case creating
    /// The backup vault has been created and is fully usable.
    case active
    /// The backup vault is being deleted.
    case deleting
    /// The backup vault is experiencing an issue and might be unusable.
    case error
    /// The backup vault is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .deleting: return 3
      case .error: return 4
      case .updating: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .deleting
      case 4: self = .error
      case 5: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .active: return try container.encode("ACTIVE")
      case .deleting: return try container.encode("DELETING")
      case .error: return try container.encode("ERROR")
      case .updating: return try container.encode("UPDATING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Holds the access restriction for the backup vault.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum AccessRestriction: Codable, Equatable, Hashable, Sendable {
    /// Access restriction not set. If user does not provide any value or pass
    /// this value, it will be changed to WITHIN_ORGANIZATION.
    case unspecified
    /// Access to or from resources outside your current project will be denied.
    case withinProject
    /// Access to or from resources outside your current organization will be
    /// denied.
    case withinOrganization
    /// No access restriction.
    case unrestricted
    /// Access to or from resources outside your current organization will be
    /// denied except for backup appliance.
    case withinOrgButUnrestrictedForBa
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .withinProject: return 1
      case .withinOrganization: return 2
      case .unrestricted: return 3
      case .withinOrgButUnrestrictedForBa: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACCESS_RESTRICTION_UNSPECIFIED"
      case .withinProject: return "WITHIN_PROJECT"
      case .withinOrganization: return "WITHIN_ORGANIZATION"
      case .unrestricted: return "UNRESTRICTED"
      case .withinOrgButUnrestrictedForBa: return "WITHIN_ORG_BUT_UNRESTRICTED_FOR_BA"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AccessRestriction/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACCESS_RESTRICTION_UNSPECIFIED": self = .unspecified
      case "WITHIN_PROJECT": self = .withinProject
      case "WITHIN_ORGANIZATION": self = .withinOrganization
      case "UNRESTRICTED": self = .unrestricted
      case "WITHIN_ORG_BUT_UNRESTRICTED_FOR_BA": self = .withinOrgButUnrestrictedForBa
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AccessRestriction/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .withinProject
      case 2: self = .withinOrganization
      case 3: self = .unrestricted
      case 4: self = .withinOrgButUnrestrictedForBa
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ACCESS_RESTRICTION_UNSPECIFIED")
      case .withinProject: return try container.encode("WITHIN_PROJECT")
      case .withinOrganization: return try container.encode("WITHIN_ORGANIZATION")
      case .unrestricted: return try container.encode("UNRESTRICTED")
      case .withinOrgButUnrestrictedForBa:
        return try container.encode("WITHIN_ORG_BUT_UNRESTRICTED_FOR_BA")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupVault"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
