// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// `BackupRule` binds the backup schedule to a retention policy.
public struct BackupRule: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Immutable. The unique id of this `BackupRule`. The `rule_id` is
  /// unique per `BackupPlan`.The `rule_id` must start with a lowercase letter
  /// followed by up to 62 lowercase letters, numbers, or hyphens. Pattern,
  /// /[a-z][a-z0-9-]{,62}/.
  public var ruleId: Swift.String = Swift.String()

  /// Required. Configures the duration for which backup data will be kept. It is
  /// defined in “days”. The value should be greater than or equal to minimum
  /// enforced retention of the backup vault.
  ///
  /// Minimum value is 1 and maximum value is 36159 for custom retention
  /// on-demand backup.
  /// Minimum and maximum values are workload specific for all other rules.
  public var backupRetentionDays: Swift.Int32 = Swift.Int32()

  /// The schedule that defines the automated backup workloads for this
  /// `BackupRule`.
  public var backupScheduleOneof: BackupScheduleOneofOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupRule().with { $0.ruleId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ruleId = CodingKeys(stringValue: "ruleId")
    static let backupRetentionDays = CodingKeys(stringValue: "backupRetentionDays")
    static let standardSchedule = CodingKeys(stringValue: "standardSchedule")

    static let _knownKeys: Set<Swift.String> = [
      "ruleId",
      "backupRetentionDays",
      "standardSchedule",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ruleId) {
      self.ruleId = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .backupRetentionDays) {
      self.backupRetentionDays = value
    }

    var backupScheduleOneof: BackupScheduleOneofOneOf? = nil
    let backupScheduleOneofCheckAndSet = {
      if backupScheduleOneof != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'backupScheduleOneof'"))
      }
      backupScheduleOneof = $0
    }
    if let standardSchedule = try container.decodeIfPresent(
      StandardSchedule.self, forKey: .standardSchedule)
    {
      try backupScheduleOneofCheckAndSet(.standardSchedule(standardSchedule))
    }
    self.backupScheduleOneof = backupScheduleOneof
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ruleId, forKey: .ruleId)
    try container.encode(self.backupRetentionDays, forKey: .backupRetentionDays)

    if let choice = self.backupScheduleOneof {
      switch choice {
      case .standardSchedule(let value):
        try container.encode(value, forKey: .standardSchedule)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The schedule that defines the automated backup workloads for this
  /// `BackupRule`.
  public enum BackupScheduleOneofOneOf: Codable, Equatable, Sendable {
    /// Optional. Defines a schedule that runs within the confines of a defined
    /// window of time.
    indirect case standardSchedule(StandardSchedule)
  }

  /// The type URL for `BackupRule`: `"type.googleapis.com/google.cloud.backupdr.v1.BackupRule"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupRule"
  }

  /// Initialize an instance of `BackupRule` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.BackupRule"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `BackupRule` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
