// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A `BackupPlan` specifies some common fields, such as `description` as well
/// as one or more `BackupRule` messages. Each `BackupRule` has a retention
/// policy and defines a schedule by which the system is to perform backup
/// workloads.
public struct BackupPlan: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource name of the `BackupPlan`.
  ///
  /// Format: `projects/{project}/locations/{location}/backupPlans/{backup_plan}`
  public var name: Swift.String = Swift.String()

  /// Optional. The description of the `BackupPlan` resource.
  ///
  /// The description allows for additional details about `BackupPlan` and its
  /// use cases to be provided. An example description is the following:  "This
  /// is a backup plan that performs a daily backup at 6pm and retains data for 3
  /// months". The description must be at most 2048 characters.
  public var description: Swift.String = Swift.String()

  /// Optional. This collection of key/value pairs allows for custom labels to be
  /// supplied by the user.  Example, {"tag": "Weekly"}.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. When the `BackupPlan` was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the `BackupPlan` was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Required. The backup rules for this `BackupPlan`. There must be at least
  /// one `BackupRule` message.
  public var backupRules: [BackupRule] = []

  /// Output only. The `State` for the `BackupPlan`.
  public var state: BackupPlan.State = BackupPlan.State()

  /// Required. The resource type to which the `BackupPlan` will be applied.
  /// Examples include, "compute.googleapis.com/Instance",
  /// "sqladmin.googleapis.com/Instance", "alloydb.googleapis.com/Cluster",
  /// "compute.googleapis.com/Disk".
  public var resourceType: Swift.String = Swift.String()

  /// Optional. `etag` is returned from the service in the response. As a user of
  /// the service, you may provide an etag value in this field to prevent stale
  /// resources.
  public var etag: Swift.String = Swift.String()

  /// Required. Resource name of backup vault which will be used as storage
  /// location for backups. Format:
  /// projects/{project}/locations/{location}/backupVaults/{backupvault}
  public var backupVault: Swift.String = Swift.String()

  /// Output only. The Google Cloud Platform Service Account to be used by the
  /// BackupVault for taking backups. Specify the email address of the Backup
  /// Vault Service Account.
  public var backupVaultServiceAccount: Swift.String = Swift.String()

  /// Optional. Applicable only for CloudSQL and AlloyDB resource_type.
  ///
  /// Configures how long logs will be stored. It is defined in “days”. This
  /// value should be greater than or equal to minimum enforced log retention
  /// duration of the backup vault.
  public var logRetentionDays: Swift.Int64 = Swift.Int64()

  /// Output only. All resource types to which backupPlan can be applied.
  public var supportedResourceTypes: [Swift.String] = []

  /// Output only. The user friendly revision ID of the `BackupPlanRevision`.
  ///
  /// Example: v0, v1, v2, etc.
  public var revisionId: Swift.String = Swift.String()

  /// Output only. The resource id of the `BackupPlanRevision`.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/backupPlans/{backup_plan}/revisions/{revision_id}`
  public var revisionName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupPlan`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupPlan().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let labels = CodingKeys(stringValue: "labels")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let backupRules = CodingKeys(stringValue: "backupRules")
    static let state = CodingKeys(stringValue: "state")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let etag = CodingKeys(stringValue: "etag")
    static let backupVault = CodingKeys(stringValue: "backupVault")
    static let backupVaultServiceAccount = CodingKeys(stringValue: "backupVaultServiceAccount")
    static let logRetentionDays = CodingKeys(stringValue: "logRetentionDays")
    static let supportedResourceTypes = CodingKeys(stringValue: "supportedResourceTypes")
    static let revisionId = CodingKeys(stringValue: "revisionId")
    static let revisionName = CodingKeys(stringValue: "revisionName")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "labels",
      "createTime",
      "updateTime",
      "backupRules",
      "state",
      "resourceType",
      "etag",
      "backupVault",
      "backupVaultServiceAccount",
      "logRetentionDays",
      "supportedResourceTypes",
      "revisionId",
      "revisionName",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([BackupRule].self, forKey: .backupRules) {
      self.backupRules = value
    }
    if let value = try container.decodeIfPresent(BackupPlan.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
      self.resourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupVault) {
      self.backupVault = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .backupVaultServiceAccount)
    {
      self.backupVaultServiceAccount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .logRetentionDays) {
      self.logRetentionDays = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .supportedResourceTypes)
    {
      self.supportedResourceTypes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .revisionId) {
      self.revisionId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .revisionName) {
      self.revisionName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.backupRules, forKey: .backupRules)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.backupVault, forKey: .backupVault)
    try container.encode(self.backupVaultServiceAccount, forKey: .backupVaultServiceAccount)
    try container.encode(self.logRetentionDays, forKey: .logRetentionDays)
    try container.encode(self.supportedResourceTypes, forKey: .supportedResourceTypes)
    try container.encode(self.revisionId, forKey: .revisionId)
    try container.encode(self.revisionName, forKey: .revisionName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// `State` enumerates the possible states for a `BackupPlan`.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// State not set.
    case unspecified
    /// The resource is being created.
    case creating
    /// The resource has been created and is fully usable.
    case active
    /// The resource is being deleted.
    case deleting
    /// The resource has been created but is not usable.
    case inactive
    /// The resource is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .deleting: return 3
      case .inactive: return 4
      case .updating: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .deleting: return "DELETING"
      case .inactive: return "INACTIVE"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "DELETING": self = .deleting
      case "INACTIVE": self = .inactive
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .deleting
      case 4: self = .inactive
      case 5: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .active: return try container.encode("ACTIVE")
      case .deleting: return try container.encode("DELETING")
      case .inactive: return try container.encode("INACTIVE")
      case .updating: return try container.encode("UPDATING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `BackupPlan`: `"type.googleapis.com/google.cloud.backupdr.v1.BackupPlan"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupPlan"
  }

  /// Initialize an instance of `BackupPlan` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.BackupPlan"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `BackupPlan` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
