// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// BackupConfigDetails has information about how the resource is configured
/// for backups and about the most recent backup taken for this configuration.
public struct BackupConfigDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The full resource name of the backup config source resource.
  /// For example,
  /// "//backupdr.googleapis.com/v1/projects/{project}/locations/{region}/backupPlans/{backupplanId}"
  /// or
  /// "//compute.googleapis.com/projects/{project}/locations/{region}/resourcePolicies/{resourcePolicyId}".
  public var backupConfigSource: Swift.String = Swift.String()

  /// Output only. The display name of the backup config source resource.
  public var backupConfigSourceDisplayName: Swift.String = Swift.String()

  /// Output only. The type of the backup config resource.
  public var type: BackupConfigDetails.Type_ = BackupConfigDetails.Type_()

  /// Output only. The state of the backup config resource.
  public var state: BackupConfigDetails.State = BackupConfigDetails.State()

  /// Output only. Point in time recovery settings of the backup configuration
  /// resource.
  public var pitrSettings: PitrSettings? = nil

  /// Output only. Timestamp of the latest successful backup created via this
  /// backup configuration.
  public var latestSuccessfulBackupTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The [full resource
  /// name](https://cloud.google.com/asset-inventory/docs/resource-name-format)
  /// of the resource that is applicable for the backup configuration. Example:
  /// "//compute.googleapis.com/projects/{project}/zones/{zone}/instances/{instance}"
  public var applicableResource: Swift.String = Swift.String()

  /// Output only. The [full resource
  /// name](https://cloud.google.com/asset-inventory/docs/resource-name-format)
  /// of the backup vault that will store the backups generated through this
  /// backup configuration. Example:
  /// "//backupdr.googleapis.com/v1/projects/{project}/locations/{region}/backupVaults/{backupvaultId}"
  public var backupVault: Swift.String = Swift.String()

  /// The locations where the backups are to be stored.
  public var backupLocations: [BackupLocation] = []

  /// The plan specific config. This depends on the value of
  /// [BackupConfigDetails.type][google.cloud.backupdr.v1.BackupConfigDetails.type].
  /// For type=BACKUPDR_BACKUP_PLAN, backup_dr_plan_config would be populated to
  /// capture information related to Google Cloud Backup and DR's Backup Plans.
  /// For type=BACKUPDR_TEMPLATE, backup_dr_template_config would be populated to
  /// capture information related to Google Cloud Backup and DR's Template
  /// details.
  ///
  /// [google.cloud.backupdr.v1.BackupConfigDetails.type]: <doc:BackupConfigDetails/type>
  public var planSpecificConfig: PlanSpecificConfigOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupConfigDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupConfigDetails().with { $0.backupConfigSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let backupConfigSource = CodingKeys(stringValue: "backupConfigSource")
    static let backupConfigSourceDisplayName = CodingKeys(
      stringValue: "backupConfigSourceDisplayName")
    static let type = CodingKeys(stringValue: "type")
    static let state = CodingKeys(stringValue: "state")
    static let pitrSettings = CodingKeys(stringValue: "pitrSettings")
    static let latestSuccessfulBackupTime = CodingKeys(stringValue: "latestSuccessfulBackupTime")
    static let applicableResource = CodingKeys(stringValue: "applicableResource")
    static let backupVault = CodingKeys(stringValue: "backupVault")
    static let backupLocations = CodingKeys(stringValue: "backupLocations")
    static let backupDrPlanConfig = CodingKeys(stringValue: "backupDrPlanConfig")
    static let backupDrTemplateConfig = CodingKeys(stringValue: "backupDrTemplateConfig")

    static let _knownKeys: Set<Swift.String> = [
      "backupConfigSource",
      "backupConfigSourceDisplayName",
      "type",
      "state",
      "pitrSettings",
      "latestSuccessfulBackupTime",
      "applicableResource",
      "backupVault",
      "backupLocations",
      "backupDrPlanConfig",
      "backupDrTemplateConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupConfigSource) {
      self.backupConfigSource = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .backupConfigSourceDisplayName)
    {
      self.backupConfigSourceDisplayName = value
    }
    if let value = try container.decodeIfPresent(BackupConfigDetails.Type_.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(BackupConfigDetails.State.self, forKey: .state) {
      self.state = value
    }
    self.pitrSettings = try container.decodeIfPresent(PitrSettings.self, forKey: .pitrSettings)
    self.latestSuccessfulBackupTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .latestSuccessfulBackupTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .applicableResource) {
      self.applicableResource = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupVault) {
      self.backupVault = value
    }
    if let value = try container.decodeIfPresent([BackupLocation].self, forKey: .backupLocations) {
      self.backupLocations = value
    }

    var planSpecificConfig: PlanSpecificConfigOneOf? = nil
    let planSpecificConfigCheckAndSet = {
      if planSpecificConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'planSpecificConfig'"))
      }
      planSpecificConfig = $0
    }
    if let backupDrPlanConfig = try container.decodeIfPresent(
      BackupDrPlanConfig.self, forKey: .backupDrPlanConfig)
    {
      try planSpecificConfigCheckAndSet(.backupDrPlanConfig(backupDrPlanConfig))
    }
    if let backupDrTemplateConfig = try container.decodeIfPresent(
      BackupDrTemplateConfig.self, forKey: .backupDrTemplateConfig)
    {
      try planSpecificConfigCheckAndSet(.backupDrTemplateConfig(backupDrTemplateConfig))
    }
    self.planSpecificConfig = planSpecificConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.backupConfigSource, forKey: .backupConfigSource)
    try container.encode(self.backupConfigSourceDisplayName, forKey: .backupConfigSourceDisplayName)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.pitrSettings, forKey: .pitrSettings)
    try container.encodeIfPresent(
      self.latestSuccessfulBackupTime, forKey: .latestSuccessfulBackupTime)
    try container.encode(self.applicableResource, forKey: .applicableResource)
    try container.encode(self.backupVault, forKey: .backupVault)
    try container.encode(self.backupLocations, forKey: .backupLocations)

    if let choice = self.planSpecificConfig {
      switch choice {
      case .backupDrPlanConfig(let value):
        try container.encode(value, forKey: .backupDrPlanConfig)
      case .backupDrTemplateConfig(let value):
        try container.encode(value, forKey: .backupDrTemplateConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Type of the backup configuration.
  /// This enum may receive new values in the future.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Hashable, Sendable {
    /// Backup config type is unspecified.
    case unspecified
    /// Backup config is Cloud SQL instance's automated backup config.
    case cloudSqlInstanceBackupConfig
    /// Backup config is Compute Engine Resource Policy.
    case computeEngineResourcePolicy
    /// Backup config is Google Cloud Backup and DR's Backup Plan.
    case backupdrBackupPlan
    /// Backup config is Google Cloud Backup and DR's Template.
    case backupdrTemplate
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cloudSqlInstanceBackupConfig: return 1
      case .computeEngineResourcePolicy: return 2
      case .backupdrBackupPlan: return 3
      case .backupdrTemplate: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .cloudSqlInstanceBackupConfig: return "CLOUD_SQL_INSTANCE_BACKUP_CONFIG"
      case .computeEngineResourcePolicy: return "COMPUTE_ENGINE_RESOURCE_POLICY"
      case .backupdrBackupPlan: return "BACKUPDR_BACKUP_PLAN"
      case .backupdrTemplate: return "BACKUPDR_TEMPLATE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "CLOUD_SQL_INSTANCE_BACKUP_CONFIG": self = .cloudSqlInstanceBackupConfig
      case "COMPUTE_ENGINE_RESOURCE_POLICY": self = .computeEngineResourcePolicy
      case "BACKUPDR_BACKUP_PLAN": self = .backupdrBackupPlan
      case "BACKUPDR_TEMPLATE": self = .backupdrTemplate
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cloudSqlInstanceBackupConfig
      case 2: self = .computeEngineResourcePolicy
      case 3: self = .backupdrBackupPlan
      case 4: self = .backupdrTemplate
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .cloudSqlInstanceBackupConfig:
        return try container.encode("CLOUD_SQL_INSTANCE_BACKUP_CONFIG")
      case .computeEngineResourcePolicy:
        return try container.encode("COMPUTE_ENGINE_RESOURCE_POLICY")
      case .backupdrBackupPlan: return try container.encode("BACKUPDR_BACKUP_PLAN")
      case .backupdrTemplate: return try container.encode("BACKUPDR_TEMPLATE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The state tells whether the backup config is active or not.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// Backup config state not set.
    case unspecified
    /// The config is in an active state protecting the resource
    case active
    /// The config is currently not protecting the resource. Either because it is
    /// disabled or the owning project has been deleted without cleanup of the
    /// actual resource.
    case inactive
    /// The config still exists but because of some error state it is not
    /// protecting the resource. Like the source project is deleted. For eg.
    /// PlanAssociation, BackupPlan is deleted.
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .inactive: return 2
      case .error: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .inactive: return "INACTIVE"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "INACTIVE": self = .inactive
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .inactive
      case 3: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .inactive: return try container.encode("INACTIVE")
      case .error: return try container.encode("ERROR")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The plan specific config. This depends on the value of
  /// [BackupConfigDetails.type][google.cloud.backupdr.v1.BackupConfigDetails.type].
  /// For type=BACKUPDR_BACKUP_PLAN, backup_dr_plan_config would be populated to
  /// capture information related to Google Cloud Backup and DR's Backup Plans.
  /// For type=BACKUPDR_TEMPLATE, backup_dr_template_config would be populated to
  /// capture information related to Google Cloud Backup and DR's Template
  /// details.
  ///
  /// [google.cloud.backupdr.v1.BackupConfigDetails.type]: <doc:BackupConfigDetails/type>
  public enum PlanSpecificConfigOneOf: Codable, Equatable, Sendable {
    /// Google Cloud Backup and DR's Backup Plan specific data.
    indirect case backupDrPlanConfig(BackupDrPlanConfig)
    /// Google Cloud Backup and DR's Template specific data.
    indirect case backupDrTemplateConfig(BackupDrTemplateConfig)
  }

  /// The type URL for `BackupConfigDetails`: `"type.googleapis.com/google.cloud.backupdr.v1.BackupConfigDetails"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupConfigDetails"
  }

  /// Initialize an instance of `BackupConfigDetails` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.BackupConfigDetails"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `BackupConfigDetails` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
