// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// BackupLock represents a single lock on a Backup resource.  An unexpired
/// lock on a Backup prevents the Backup from being deleted.
public struct BackupLock: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The time after which this lock is not considered valid and will
  /// no longer protect the Backup from deletion.
  public var lockUntilTime: GoogleWKT.WKTTimestamp? = nil

  /// Metadata about the owner and reason for the lock.
  public var clientLockInfo: ClientLockInfoOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupLock`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupLock().with { $0.lockUntilTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let lockUntilTime = CodingKeys(stringValue: "lockUntilTime")
    static let backupApplianceLockInfo = CodingKeys(stringValue: "backupApplianceLockInfo")
    static let serviceLockInfo = CodingKeys(stringValue: "serviceLockInfo")

    static let _knownKeys: Set<Swift.String> = [
      "lockUntilTime",
      "backupApplianceLockInfo",
      "serviceLockInfo",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.lockUntilTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lockUntilTime)

    var clientLockInfo: ClientLockInfoOneOf? = nil
    let clientLockInfoCheckAndSet = {
      if clientLockInfo != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'clientLockInfo'"))
      }
      clientLockInfo = $0
    }
    if let backupApplianceLockInfo = try container.decodeIfPresent(
      BackupApplianceLockInfo.self, forKey: .backupApplianceLockInfo)
    {
      try clientLockInfoCheckAndSet(.backupApplianceLockInfo(backupApplianceLockInfo))
    }
    if let serviceLockInfo = try container.decodeIfPresent(
      ServiceLockInfo.self, forKey: .serviceLockInfo)
    {
      try clientLockInfoCheckAndSet(.serviceLockInfo(serviceLockInfo))
    }
    self.clientLockInfo = clientLockInfo
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.lockUntilTime, forKey: .lockUntilTime)

    if let choice = self.clientLockInfo {
      switch choice {
      case .backupApplianceLockInfo(let value):
        try container.encode(value, forKey: .backupApplianceLockInfo)
      case .serviceLockInfo(let value):
        try container.encode(value, forKey: .serviceLockInfo)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Metadata about the owner and reason for the lock.
  public enum ClientLockInfoOneOf: Codable, Equatable, Sendable {
    /// If the client is a backup and recovery appliance, this
    /// contains metadata about why the lock exists.
    indirect case backupApplianceLockInfo(BackupApplianceLockInfo)
    /// Output only. Contains metadata about the lock exist for Google Cloud
    /// native backups.
    indirect case serviceLockInfo(ServiceLockInfo)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupLock"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
