// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// BackupConfigInfo has information about how the resource is configured
/// for Backup and about the most recent backup to this vault.
public struct BackupConfigInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The status of the last backup to this BackupVault
  public var lastBackupState: BackupConfigInfo.LastBackupState = BackupConfigInfo.LastBackupState()

  /// Output only. If the last backup were successful, this field has the
  /// consistency date.
  public var lastSuccessfulBackupConsistencyTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. If the last backup failed, this field has the error message.
  public var lastBackupError: GoogleRpc.Status? = nil

  /// Configuration Info has the resource format-specific configuration.
  public var backupConfig: BackupConfigOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupConfigInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupConfigInfo().with { $0.lastBackupState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let lastBackupState = CodingKeys(stringValue: "lastBackupState")
    static let lastSuccessfulBackupConsistencyTime = CodingKeys(
      stringValue: "lastSuccessfulBackupConsistencyTime")
    static let lastBackupError = CodingKeys(stringValue: "lastBackupError")
    static let gcpBackupConfig = CodingKeys(stringValue: "gcpBackupConfig")
    static let backupApplianceBackupConfig = CodingKeys(stringValue: "backupApplianceBackupConfig")

    static let _knownKeys: Set<Swift.String> = [
      "lastBackupState",
      "lastSuccessfulBackupConsistencyTime",
      "lastBackupError",
      "gcpBackupConfig",
      "backupApplianceBackupConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      BackupConfigInfo.LastBackupState.self, forKey: .lastBackupState)
    {
      self.lastBackupState = value
    }
    self.lastSuccessfulBackupConsistencyTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastSuccessfulBackupConsistencyTime)
    self.lastBackupError = try container.decodeIfPresent(
      GoogleRpc.Status.self, forKey: .lastBackupError)

    var backupConfig: BackupConfigOneOf? = nil
    let backupConfigCheckAndSet = {
      if backupConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'backupConfig'"))
      }
      backupConfig = $0
    }
    if let gcpBackupConfig = try container.decodeIfPresent(
      GcpBackupConfig.self, forKey: .gcpBackupConfig)
    {
      try backupConfigCheckAndSet(.gcpBackupConfig(gcpBackupConfig))
    }
    if let backupApplianceBackupConfig = try container.decodeIfPresent(
      BackupApplianceBackupConfig.self, forKey: .backupApplianceBackupConfig)
    {
      try backupConfigCheckAndSet(.backupApplianceBackupConfig(backupApplianceBackupConfig))
    }
    self.backupConfig = backupConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.lastBackupState, forKey: .lastBackupState)
    try container.encodeIfPresent(
      self.lastSuccessfulBackupConsistencyTime, forKey: .lastSuccessfulBackupConsistencyTime)
    try container.encodeIfPresent(self.lastBackupError, forKey: .lastBackupError)

    if let choice = self.backupConfig {
      switch choice {
      case .gcpBackupConfig(let value):
        try container.encode(value, forKey: .gcpBackupConfig)
      case .backupApplianceBackupConfig(let value):
        try container.encode(value, forKey: .backupApplianceBackupConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// LastBackupstate tracks whether the last backup was not yet started,
  /// successful, failed, or could not be run because of the lack of permissions.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum LastBackupState: Codable, Equatable, Hashable, Sendable {
    /// Status not set.
    case unspecified
    /// The first backup has not yet completed
    case firstBackupPending
    /// The most recent backup was successful
    case succeeded
    /// The most recent backup failed
    case failed
    /// The most recent backup could not be run/failed because of the lack of
    /// permissions
    case permissionDenied
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .firstBackupPending: return 1
      case .succeeded: return 2
      case .failed: return 3
      case .permissionDenied: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "LAST_BACKUP_STATE_UNSPECIFIED"
      case .firstBackupPending: return "FIRST_BACKUP_PENDING"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .permissionDenied: return "PERMISSION_DENIED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LastBackupState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LAST_BACKUP_STATE_UNSPECIFIED": self = .unspecified
      case "FIRST_BACKUP_PENDING": self = .firstBackupPending
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "PERMISSION_DENIED": self = .permissionDenied
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LastBackupState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .firstBackupPending
      case 2: self = .succeeded
      case 3: self = .failed
      case 4: self = .permissionDenied
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("LAST_BACKUP_STATE_UNSPECIFIED")
      case .firstBackupPending: return try container.encode("FIRST_BACKUP_PENDING")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .failed: return try container.encode("FAILED")
      case .permissionDenied: return try container.encode("PERMISSION_DENIED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Configuration Info has the resource format-specific configuration.
  public enum BackupConfigOneOf: Codable, Equatable, Sendable {
    /// Configuration for a Google Cloud resource.
    indirect case gcpBackupConfig(GcpBackupConfig)
    /// Configuration for an application backed up by a Backup Appliance.
    indirect case backupApplianceBackupConfig(BackupApplianceBackupConfig)
  }

  /// The type URL for `BackupConfigInfo`: `"type.googleapis.com/google.cloud.backupdr.v1.BackupConfigInfo"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.BackupConfigInfo"
  }

  /// Initialize an instance of `BackupConfigInfo` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.BackupConfigInfo"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `BackupConfigInfo` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
