// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// CloudSqlInstanceBackupProperties represents Cloud SQL Instance
/// Backup properties.
public struct CloudSqlInstanceBackupProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The installed database version of the Cloud SQL instance
  /// when the backup was taken.
  public var databaseInstalledVersion: Swift.String = Swift.String()

  /// Output only. Whether the backup is a final backup.
  public var finalBackup: Swift.Bool = Swift.Bool()

  /// Output only. The source instance of the backup.
  /// Format:
  /// projects/{project}/instances/{instance}
  public var sourceInstance: Swift.String = Swift.String()

  /// Output only. The instance creation timestamp.
  public var instanceCreateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The tier (or machine type) for this instance. Example:
  /// `db-custom-1-3840`
  public var instanceTier: Swift.String = Swift.String()

  /// Output only. The instance delete timestamp.
  public var instanceDeleteTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudSqlInstanceBackupProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudSqlInstanceBackupProperties().with { $0.databaseInstalledVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let databaseInstalledVersion = CodingKeys(stringValue: "databaseInstalledVersion")
    static let finalBackup = CodingKeys(stringValue: "finalBackup")
    static let sourceInstance = CodingKeys(stringValue: "sourceInstance")
    static let instanceCreateTime = CodingKeys(stringValue: "instanceCreateTime")
    static let instanceTier = CodingKeys(stringValue: "instanceTier")
    static let instanceDeleteTime = CodingKeys(stringValue: "instanceDeleteTime")

    static let _knownKeys: Set<Swift.String> = [
      "databaseInstalledVersion",
      "finalBackup",
      "sourceInstance",
      "instanceCreateTime",
      "instanceTier",
      "instanceDeleteTime",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .databaseInstalledVersion)
    {
      self.databaseInstalledVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .finalBackup) {
      self.finalBackup = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceInstance) {
      self.sourceInstance = value
    }
    self.instanceCreateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .instanceCreateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceTier) {
      self.instanceTier = value
    }
    self.instanceDeleteTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .instanceDeleteTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.databaseInstalledVersion, forKey: .databaseInstalledVersion)
    try container.encode(self.finalBackup, forKey: .finalBackup)
    try container.encode(self.sourceInstance, forKey: .sourceInstance)
    try container.encodeIfPresent(self.instanceCreateTime, forKey: .instanceCreateTime)
    try container.encode(self.instanceTier, forKey: .instanceTier)
    try container.encodeIfPresent(self.instanceDeleteTime, forKey: .instanceDeleteTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `CloudSqlInstanceBackupProperties`: `"type.googleapis.com/google.cloud.backupdr.v1.CloudSqlInstanceBackupProperties"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.CloudSqlInstanceBackupProperties"
  }

  /// Initialize an instance of `CloudSqlInstanceBackupProperties` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.CloudSqlInstanceBackupProperties"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `CloudSqlInstanceBackupProperties` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
