// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ComputeInstanceBackupProperties represents Compute Engine instance backup
/// properties.
public struct ComputeInstanceBackupProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// An optional text description for the instances that are created from these
  /// properties.
  public var description: Swift.String? = nil

  /// A list of tags to apply to the instances that are created from these
  /// properties. The tags identify valid sources or targets for network
  /// firewalls. The setTags method can modify this list of tags. Each tag within
  /// the list must comply with RFC1035 (https://www.ietf.org/rfc/rfc1035.txt).
  public var tags: Tags? = nil

  /// The machine type to use for instances that are created from these
  /// properties.
  public var machineType: Swift.String? = nil

  /// Enables instances created based on these properties to send packets with
  /// source IP addresses other than their own and receive packets with
  /// destination IP addresses other than their own. If these instances will be
  /// used as an IP gateway or it will be set as the next-hop in a Route
  /// resource, specify `true`. If unsure, leave this set to `false`. See the
  /// https://cloud.google.com/vpc/docs/using-routes#canipforward
  /// documentation for more information.
  public var canIpForward: Swift.Bool? = nil

  /// An array of network access configurations for this interface.
  public var networkInterface: [NetworkInterface] = []

  /// An array of disks that are associated with the instances that are created
  /// from these properties.
  public var disk: [AttachedDisk] = []

  /// The metadata key/value pairs to assign to instances that are created from
  /// these properties. These pairs can consist of custom metadata or predefined
  /// keys. See https://cloud.google.com/compute/docs/metadata/overview for more
  /// information.
  public var metadata: Metadata? = nil

  /// A list of service accounts with specified scopes. Access tokens for these
  /// service accounts are available to the instances that are created from
  /// these properties. Use metadata queries to obtain the access tokens for
  /// these instances.
  public var serviceAccount: [ServiceAccount] = []

  /// Specifies the scheduling options for the instances that are created from
  /// these properties.
  public var scheduling: Scheduling? = nil

  /// A list of guest accelerator cards' type and count to use for instances
  /// created from these properties.
  public var guestAccelerator: [AcceleratorConfig] = []

  /// Minimum cpu/platform to be used by instances. The instance may be
  /// scheduled on the specified or newer cpu/platform. Applicable values are the
  /// friendly names of CPU platforms, such as
  /// `minCpuPlatform: Intel Haswell` or `minCpuPlatform: Intel Sandy Bridge`.
  /// For more information, read
  /// https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform.
  public var minCpuPlatform: Swift.String? = nil

  /// KeyRevocationActionType of the instance. Supported options are "STOP" and
  /// "NONE". The default value is "NONE" if it is not specified.
  public var keyRevocationActionType: KeyRevocationActionType? = nil

  /// The source instance used to create this backup. This can be a partial or
  /// full URL to the resource. For example, the following are valid values:
  ///   -https://www.googleapis.com/compute/v1/projects/project/zones/zone/instances/instance
  ///   -projects/project/zones/zone/instances/instance
  public var sourceInstance: Swift.String? = nil

  /// Labels to apply to instances that are created from these properties.
  public var labels: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ComputeInstanceBackupProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeInstanceBackupProperties().with { $0.description = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let description = CodingKeys(stringValue: "description")
    static let tags = CodingKeys(stringValue: "tags")
    static let machineType = CodingKeys(stringValue: "machineType")
    static let canIpForward = CodingKeys(stringValue: "canIpForward")
    static let networkInterface = CodingKeys(stringValue: "networkInterface")
    static let disk = CodingKeys(stringValue: "disk")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let scheduling = CodingKeys(stringValue: "scheduling")
    static let guestAccelerator = CodingKeys(stringValue: "guestAccelerator")
    static let minCpuPlatform = CodingKeys(stringValue: "minCpuPlatform")
    static let keyRevocationActionType = CodingKeys(stringValue: "keyRevocationActionType")
    static let sourceInstance = CodingKeys(stringValue: "sourceInstance")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "description",
      "tags",
      "machineType",
      "canIpForward",
      "networkInterface",
      "disk",
      "metadata",
      "serviceAccount",
      "scheduling",
      "guestAccelerator",
      "minCpuPlatform",
      "keyRevocationActionType",
      "sourceInstance",
      "labels",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
    self.tags = try container.decodeIfPresent(Tags.self, forKey: .tags)
    self.machineType = try container.decodeIfPresent(Swift.String.self, forKey: .machineType)
    self.canIpForward = try container.decodeIfPresent(Swift.Bool.self, forKey: .canIpForward)
    if let value = try container.decodeIfPresent([NetworkInterface].self, forKey: .networkInterface)
    {
      self.networkInterface = value
    }
    if let value = try container.decodeIfPresent([AttachedDisk].self, forKey: .disk) {
      self.disk = value
    }
    self.metadata = try container.decodeIfPresent(Metadata.self, forKey: .metadata)
    if let value = try container.decodeIfPresent([ServiceAccount].self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    self.scheduling = try container.decodeIfPresent(Scheduling.self, forKey: .scheduling)
    if let value = try container.decodeIfPresent(
      [AcceleratorConfig].self, forKey: .guestAccelerator)
    {
      self.guestAccelerator = value
    }
    self.minCpuPlatform = try container.decodeIfPresent(Swift.String.self, forKey: .minCpuPlatform)
    self.keyRevocationActionType = try container.decodeIfPresent(
      KeyRevocationActionType.self, forKey: .keyRevocationActionType)
    self.sourceInstance = try container.decodeIfPresent(Swift.String.self, forKey: .sourceInstance)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.description, forKey: .description)
    try container.encodeIfPresent(self.tags, forKey: .tags)
    try container.encodeIfPresent(self.machineType, forKey: .machineType)
    try container.encodeIfPresent(self.canIpForward, forKey: .canIpForward)
    try container.encode(self.networkInterface, forKey: .networkInterface)
    try container.encode(self.disk, forKey: .disk)
    try container.encodeIfPresent(self.metadata, forKey: .metadata)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encodeIfPresent(self.scheduling, forKey: .scheduling)
    try container.encode(self.guestAccelerator, forKey: .guestAccelerator)
    try container.encodeIfPresent(self.minCpuPlatform, forKey: .minCpuPlatform)
    try container.encodeIfPresent(self.keyRevocationActionType, forKey: .keyRevocationActionType)
    try container.encodeIfPresent(self.sourceInstance, forKey: .sourceInstance)
    try container.encode(self.labels, forKey: .labels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.ComputeInstanceBackupProperties"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
