// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ComputeInstanceRestoreProperties represents Compute Engine instance
/// properties to be overridden during restore.
public struct ComputeInstanceRestoreProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Name of the compute instance.
  public var name: Swift.String? = nil

  /// Optional. Controls for advanced machine-related behavior features.
  public var advancedMachineFeatures: AdvancedMachineFeatures? = nil

  /// Optional. Allows this instance to send and receive packets with
  /// non-matching destination or source IPs.
  public var canIpForward: Swift.Bool? = nil

  /// Optional. Controls Confidential compute options on the instance
  public var confidentialInstanceConfig: ConfidentialInstanceConfig? = nil

  /// Optional. Whether the resource should be protected against deletion.
  public var deletionProtection: Swift.Bool? = nil

  /// Optional. An optional description of this resource. Provide this property
  /// when you create the resource.
  public var description: Swift.String? = nil

  /// Optional. Array of disks associated with this instance. Persistent disks
  /// must be created before you can assign them. Source regional persistent
  /// disks will be restored with default replica zones if not specified.
  public var disks: [AttachedDisk] = []

  /// Optional. Enables display device for the instance.
  public var displayDevice: DisplayDevice? = nil

  /// Optional. A list of the type and count of accelerator cards attached to the
  /// instance.
  public var guestAccelerators: [AcceleratorConfig] = []

  /// Optional. Specifies the hostname of the instance. The specified hostname
  /// must be RFC1035 compliant. If hostname is not specified, the default
  /// hostname is [INSTANCE_NAME].c.[PROJECT_ID].internal when using the global
  /// DNS, and [INSTANCE_NAME].[ZONE].c.[PROJECT_ID].internal when using zonal
  /// DNS.
  public var hostname: Swift.String? = nil

  /// Optional. Encrypts suspended data for an instance with a
  /// customer-managed encryption key.
  public var instanceEncryptionKey: CustomerEncryptionKey? = nil

  /// Optional. KeyRevocationActionType of the instance.
  public var keyRevocationActionType: KeyRevocationActionType? = nil

  /// Optional. Labels to apply to this instance.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Full or partial URL of the machine type resource to use for this
  /// instance.
  public var machineType: Swift.String? = nil

  /// Optional. This includes custom metadata and predefined keys.
  public var metadata: Metadata? = nil

  /// Optional. Minimum CPU platform to use for this instance.
  public var minCpuPlatform: Swift.String? = nil

  /// Optional. An array of network configurations for this instance. These
  /// specify how interfaces are configured to interact with other network
  /// services, such as connecting to the internet. Multiple interfaces are
  /// supported per instance. Required to restore in different project or region.
  public var networkInterfaces: [NetworkInterface] = []

  /// Optional. Configure network performance such as egress bandwidth tier.
  public var networkPerformanceConfig: NetworkPerformanceConfig? = nil

  /// Input only. Additional params passed with the request, but not persisted
  /// as part of resource payload.
  public var params: InstanceParams? = nil

  /// Optional. The private IPv6 google access type for the VM.
  /// If not specified, use INHERIT_FROM_SUBNETWORK as default.
  public var privateIpv6GoogleAccess:
    ComputeInstanceRestoreProperties.InstancePrivateIpv6GoogleAccess? = nil

  /// Optional. Specifies the reservations that this instance can consume from.
  public var allocationAffinity: AllocationAffinity? = nil

  /// Optional. Resource policies applied to this instance.
  /// By default, no resource policies will be applied.
  public var resourcePolicies: [Swift.String] = []

  /// Optional. Sets the scheduling options for this instance.
  public var scheduling: Scheduling? = nil

  /// Optional. A list of service accounts, with their specified scopes,
  /// authorized for this instance. Only one service account per VM instance is
  /// supported.
  public var serviceAccounts: [ServiceAccount] = []

  /// Optional. Tags to apply to this instance. Tags are used to identify valid
  /// sources or targets for network firewalls and are specified by the client
  /// during instance creation.
  public var tags: Tags? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ComputeInstanceRestoreProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeInstanceRestoreProperties().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let advancedMachineFeatures = CodingKeys(stringValue: "advancedMachineFeatures")
    static let canIpForward = CodingKeys(stringValue: "canIpForward")
    static let confidentialInstanceConfig = CodingKeys(stringValue: "confidentialInstanceConfig")
    static let deletionProtection = CodingKeys(stringValue: "deletionProtection")
    static let description = CodingKeys(stringValue: "description")
    static let disks = CodingKeys(stringValue: "disks")
    static let displayDevice = CodingKeys(stringValue: "displayDevice")
    static let guestAccelerators = CodingKeys(stringValue: "guestAccelerators")
    static let hostname = CodingKeys(stringValue: "hostname")
    static let instanceEncryptionKey = CodingKeys(stringValue: "instanceEncryptionKey")
    static let keyRevocationActionType = CodingKeys(stringValue: "keyRevocationActionType")
    static let labels = CodingKeys(stringValue: "labels")
    static let machineType = CodingKeys(stringValue: "machineType")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let minCpuPlatform = CodingKeys(stringValue: "minCpuPlatform")
    static let networkInterfaces = CodingKeys(stringValue: "networkInterfaces")
    static let networkPerformanceConfig = CodingKeys(stringValue: "networkPerformanceConfig")
    static let params = CodingKeys(stringValue: "params")
    static let privateIpv6GoogleAccess = CodingKeys(stringValue: "privateIpv6GoogleAccess")
    static let allocationAffinity = CodingKeys(stringValue: "reservationAffinity")
    static let resourcePolicies = CodingKeys(stringValue: "resourcePolicies")
    static let scheduling = CodingKeys(stringValue: "scheduling")
    static let serviceAccounts = CodingKeys(stringValue: "serviceAccounts")
    static let tags = CodingKeys(stringValue: "tags")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "advancedMachineFeatures",
      "canIpForward",
      "confidentialInstanceConfig",
      "deletionProtection",
      "description",
      "disks",
      "displayDevice",
      "guestAccelerators",
      "hostname",
      "instanceEncryptionKey",
      "keyRevocationActionType",
      "labels",
      "machineType",
      "metadata",
      "minCpuPlatform",
      "networkInterfaces",
      "networkPerformanceConfig",
      "params",
      "privateIpv6GoogleAccess",
      "reservationAffinity",
      "resourcePolicies",
      "scheduling",
      "serviceAccounts",
      "tags",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decodeIfPresent(Swift.String.self, forKey: .name)
    self.advancedMachineFeatures = try container.decodeIfPresent(
      AdvancedMachineFeatures.self, forKey: .advancedMachineFeatures)
    self.canIpForward = try container.decodeIfPresent(Swift.Bool.self, forKey: .canIpForward)
    self.confidentialInstanceConfig = try container.decodeIfPresent(
      ConfidentialInstanceConfig.self, forKey: .confidentialInstanceConfig)
    self.deletionProtection = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .deletionProtection)
    self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
    if let value = try container.decodeIfPresent([AttachedDisk].self, forKey: .disks) {
      self.disks = value
    }
    self.displayDevice = try container.decodeIfPresent(DisplayDevice.self, forKey: .displayDevice)
    if let value = try container.decodeIfPresent(
      [AcceleratorConfig].self, forKey: .guestAccelerators)
    {
      self.guestAccelerators = value
    }
    self.hostname = try container.decodeIfPresent(Swift.String.self, forKey: .hostname)
    self.instanceEncryptionKey = try container.decodeIfPresent(
      CustomerEncryptionKey.self, forKey: .instanceEncryptionKey)
    self.keyRevocationActionType = try container.decodeIfPresent(
      KeyRevocationActionType.self, forKey: .keyRevocationActionType)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.machineType = try container.decodeIfPresent(Swift.String.self, forKey: .machineType)
    self.metadata = try container.decodeIfPresent(Metadata.self, forKey: .metadata)
    self.minCpuPlatform = try container.decodeIfPresent(Swift.String.self, forKey: .minCpuPlatform)
    if let value = try container.decodeIfPresent(
      [NetworkInterface].self, forKey: .networkInterfaces)
    {
      self.networkInterfaces = value
    }
    self.networkPerformanceConfig = try container.decodeIfPresent(
      NetworkPerformanceConfig.self, forKey: .networkPerformanceConfig)
    self.params = try container.decodeIfPresent(InstanceParams.self, forKey: .params)
    self.privateIpv6GoogleAccess = try container.decodeIfPresent(
      ComputeInstanceRestoreProperties.InstancePrivateIpv6GoogleAccess.self,
      forKey: .privateIpv6GoogleAccess)
    self.allocationAffinity = try container.decodeIfPresent(
      AllocationAffinity.self, forKey: .allocationAffinity)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .resourcePolicies) {
      self.resourcePolicies = value
    }
    self.scheduling = try container.decodeIfPresent(Scheduling.self, forKey: .scheduling)
    if let value = try container.decodeIfPresent([ServiceAccount].self, forKey: .serviceAccounts) {
      self.serviceAccounts = value
    }
    self.tags = try container.decodeIfPresent(Tags.self, forKey: .tags)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.name, forKey: .name)
    try container.encodeIfPresent(self.advancedMachineFeatures, forKey: .advancedMachineFeatures)
    try container.encodeIfPresent(self.canIpForward, forKey: .canIpForward)
    try container.encodeIfPresent(
      self.confidentialInstanceConfig, forKey: .confidentialInstanceConfig)
    try container.encodeIfPresent(self.deletionProtection, forKey: .deletionProtection)
    try container.encodeIfPresent(self.description, forKey: .description)
    try container.encode(self.disks, forKey: .disks)
    try container.encodeIfPresent(self.displayDevice, forKey: .displayDevice)
    try container.encode(self.guestAccelerators, forKey: .guestAccelerators)
    try container.encodeIfPresent(self.hostname, forKey: .hostname)
    try container.encodeIfPresent(self.instanceEncryptionKey, forKey: .instanceEncryptionKey)
    try container.encodeIfPresent(self.keyRevocationActionType, forKey: .keyRevocationActionType)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.machineType, forKey: .machineType)
    try container.encodeIfPresent(self.metadata, forKey: .metadata)
    try container.encodeIfPresent(self.minCpuPlatform, forKey: .minCpuPlatform)
    try container.encode(self.networkInterfaces, forKey: .networkInterfaces)
    try container.encodeIfPresent(self.networkPerformanceConfig, forKey: .networkPerformanceConfig)
    try container.encodeIfPresent(self.params, forKey: .params)
    try container.encodeIfPresent(self.privateIpv6GoogleAccess, forKey: .privateIpv6GoogleAccess)
    try container.encodeIfPresent(self.allocationAffinity, forKey: .allocationAffinity)
    try container.encode(self.resourcePolicies, forKey: .resourcePolicies)
    try container.encodeIfPresent(self.scheduling, forKey: .scheduling)
    try container.encode(self.serviceAccounts, forKey: .serviceAccounts)
    try container.encodeIfPresent(self.tags, forKey: .tags)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The private IPv6 google access type for the VMs.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum InstancePrivateIpv6GoogleAccess: Codable, Equatable, Hashable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Each network interface inherits PrivateIpv6GoogleAccess from its
    /// subnetwork.
    case inheritFromSubnetwork
    /// Outbound private IPv6 access from VMs in this subnet to Google services.
    /// If specified, the subnetwork who is attached to the instance's default
    /// network interface will be assigned an internal IPv6 prefix if it doesn't
    /// have before.
    case enableOutboundVmAccessToGoogle
    /// Bidirectional private IPv6 access to/from Google services. If
    /// specified, the subnetwork who is attached to the instance's default
    /// network interface will be assigned an internal IPv6 prefix if it doesn't
    /// have before.
    case enableBidirectionalAccessToGoogle
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inheritFromSubnetwork: return 1
      case .enableOutboundVmAccessToGoogle: return 2
      case .enableBidirectionalAccessToGoogle: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INSTANCE_PRIVATE_IPV6_GOOGLE_ACCESS_UNSPECIFIED"
      case .inheritFromSubnetwork: return "INHERIT_FROM_SUBNETWORK"
      case .enableOutboundVmAccessToGoogle: return "ENABLE_OUTBOUND_VM_ACCESS_TO_GOOGLE"
      case .enableBidirectionalAccessToGoogle: return "ENABLE_BIDIRECTIONAL_ACCESS_TO_GOOGLE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InstancePrivateIpv6GoogleAccess/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INSTANCE_PRIVATE_IPV6_GOOGLE_ACCESS_UNSPECIFIED": self = .unspecified
      case "INHERIT_FROM_SUBNETWORK": self = .inheritFromSubnetwork
      case "ENABLE_OUTBOUND_VM_ACCESS_TO_GOOGLE": self = .enableOutboundVmAccessToGoogle
      case "ENABLE_BIDIRECTIONAL_ACCESS_TO_GOOGLE": self = .enableBidirectionalAccessToGoogle
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InstancePrivateIpv6GoogleAccess/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inheritFromSubnetwork
      case 2: self = .enableOutboundVmAccessToGoogle
      case 3: self = .enableBidirectionalAccessToGoogle
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified:
        return try container.encode("INSTANCE_PRIVATE_IPV6_GOOGLE_ACCESS_UNSPECIFIED")
      case .inheritFromSubnetwork: return try container.encode("INHERIT_FROM_SUBNETWORK")
      case .enableOutboundVmAccessToGoogle:
        return try container.encode("ENABLE_OUTBOUND_VM_ACCESS_TO_GOOGLE")
      case .enableBidirectionalAccessToGoogle:
        return try container.encode("ENABLE_BIDIRECTIONAL_ACCESS_TO_GOOGLE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.ComputeInstanceRestoreProperties"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
