// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A customer-supplied encryption key.
public struct CustomerEncryptionKey: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The service account being used for the encryption request for the
  /// given KMS key. If absent, the Compute Engine default service account is
  /// used.
  public var kmsKeyServiceAccount: Swift.String? = nil

  /// The key to use for encryption.
  public var key: KeyOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CustomerEncryptionKey`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CustomerEncryptionKey().with { $0.rawKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let rawKey = CodingKeys(stringValue: "rawKey")
    static let rsaEncryptedKey = CodingKeys(stringValue: "rsaEncryptedKey")
    static let kmsKeyName = CodingKeys(stringValue: "kmsKeyName")
    static let kmsKeyServiceAccount = CodingKeys(stringValue: "kmsKeyServiceAccount")

    static let _knownKeys: Set<Swift.String> = [
      "rawKey",
      "rsaEncryptedKey",
      "kmsKeyName",
      "kmsKeyServiceAccount",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.kmsKeyServiceAccount = try container.decodeIfPresent(
      Swift.String.self, forKey: .kmsKeyServiceAccount)

    var key: KeyOneOf? = nil
    let keyCheckAndSet = {
      if key != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'key'")
        )
      }
      key = $0
    }
    if let rawKey = try container.decodeIfPresent(Swift.String.self, forKey: .rawKey) {
      try keyCheckAndSet(.rawKey(rawKey))
    }
    if let rsaEncryptedKey = try container.decodeIfPresent(
      Swift.String.self, forKey: .rsaEncryptedKey)
    {
      try keyCheckAndSet(.rsaEncryptedKey(rsaEncryptedKey))
    }
    if let kmsKeyName = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKeyName) {
      try keyCheckAndSet(.kmsKeyName(kmsKeyName))
    }
    self.key = key
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.kmsKeyServiceAccount, forKey: .kmsKeyServiceAccount)

    if let choice = self.key {
      switch choice {
      case .rawKey(let value):
        try container.encode(value, forKey: .rawKey)
      case .rsaEncryptedKey(let value):
        try container.encode(value, forKey: .rsaEncryptedKey)
      case .kmsKeyName(let value):
        try container.encode(value, forKey: .kmsKeyName)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The key to use for encryption.
  public enum KeyOneOf: Codable, Equatable, Sendable {
    /// Optional. Specifies a 256-bit customer-supplied
    /// encryption key.
    case rawKey(Swift.String)
    /// Optional. RSA-wrapped 2048-bit
    /// customer-supplied encryption key to either encrypt or decrypt this
    /// resource.
    case rsaEncryptedKey(Swift.String)
    /// Optional. The name of the encryption key that is stored in Google Cloud
    /// KMS.
    case kmsKeyName(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.CustomerEncryptionKey"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
