// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// DataSourceGcpResource is used for protected resources that are Google Cloud
/// Resources. This name is easeier to understand than GcpResourceDataSource or
/// GcpDataSourceResource
public struct DataSourceGcpResource: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Full resource pathname URL of the source Google Cloud
  /// resource.
  public var gcpResourcename: Swift.String = Swift.String()

  /// Location of the resource: <region>/<zone>/"global"/"unspecified".
  public var location: Swift.String = Swift.String()

  /// The type of the Google Cloud resource. Use the Unified Resource Type,
  /// eg. compute.googleapis.com/Instance.
  public var type: Swift.String = Swift.String()

  /// gcp_Properties has properties of the Google Cloud Resource.
  public var gcpResourceProperties: GcpResourcePropertiesOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataSourceGcpResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSourceGcpResource().with { $0.gcpResourcename = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcpResourcename = CodingKeys(stringValue: "gcpResourcename")
    static let location = CodingKeys(stringValue: "location")
    static let type = CodingKeys(stringValue: "type")
    static let computeInstanceDatasourceProperties = CodingKeys(
      stringValue: "computeInstanceDatasourceProperties")
    static let cloudSqlInstanceDatasourceProperties = CodingKeys(
      stringValue: "cloudSqlInstanceDatasourceProperties")
    static let alloyDbClusterDatasourceProperties = CodingKeys(
      stringValue: "alloyDbClusterDatasourceProperties")
    static let diskDatasourceProperties = CodingKeys(stringValue: "diskDatasourceProperties")

    static let _knownKeys: Set<Swift.String> = [
      "gcpResourcename",
      "location",
      "type",
      "computeInstanceDatasourceProperties",
      "cloudSqlInstanceDatasourceProperties",
      "alloyDbClusterDatasourceProperties",
      "diskDatasourceProperties",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gcpResourcename) {
      self.gcpResourcename = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
      self.location = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }

    var gcpResourceProperties: GcpResourcePropertiesOneOf? = nil
    let gcpResourcePropertiesCheckAndSet = {
      if gcpResourceProperties != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'gcpResourceProperties'"))
      }
      gcpResourceProperties = $0
    }
    if let computeInstanceDatasourceProperties = try container.decodeIfPresent(
      ComputeInstanceDataSourceProperties.self, forKey: .computeInstanceDatasourceProperties)
    {
      try gcpResourcePropertiesCheckAndSet(
        .computeInstanceDatasourceProperties(computeInstanceDatasourceProperties))
    }
    if let cloudSqlInstanceDatasourceProperties = try container.decodeIfPresent(
      CloudSqlInstanceDataSourceProperties.self, forKey: .cloudSqlInstanceDatasourceProperties)
    {
      try gcpResourcePropertiesCheckAndSet(
        .cloudSqlInstanceDatasourceProperties(cloudSqlInstanceDatasourceProperties))
    }
    if let alloyDbClusterDatasourceProperties = try container.decodeIfPresent(
      AlloyDBClusterDataSourceProperties.self, forKey: .alloyDbClusterDatasourceProperties)
    {
      try gcpResourcePropertiesCheckAndSet(
        .alloyDbClusterDatasourceProperties(alloyDbClusterDatasourceProperties))
    }
    if let diskDatasourceProperties = try container.decodeIfPresent(
      DiskDataSourceProperties.self, forKey: .diskDatasourceProperties)
    {
      try gcpResourcePropertiesCheckAndSet(.diskDatasourceProperties(diskDatasourceProperties))
    }
    self.gcpResourceProperties = gcpResourceProperties
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.gcpResourcename, forKey: .gcpResourcename)
    try container.encode(self.location, forKey: .location)
    try container.encode(self.type, forKey: .type)

    if let choice = self.gcpResourceProperties {
      switch choice {
      case .computeInstanceDatasourceProperties(let value):
        try container.encode(value, forKey: .computeInstanceDatasourceProperties)
      case .cloudSqlInstanceDatasourceProperties(let value):
        try container.encode(value, forKey: .cloudSqlInstanceDatasourceProperties)
      case .alloyDbClusterDatasourceProperties(let value):
        try container.encode(value, forKey: .alloyDbClusterDatasourceProperties)
      case .diskDatasourceProperties(let value):
        try container.encode(value, forKey: .diskDatasourceProperties)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// gcp_Properties has properties of the Google Cloud Resource.
  public enum GcpResourcePropertiesOneOf: Codable, Equatable, Sendable {
    /// ComputeInstanceDataSourceProperties has a subset of Compute Instance
    /// properties that are useful at the Datasource level.
    indirect case computeInstanceDatasourceProperties(ComputeInstanceDataSourceProperties)
    /// Output only. CloudSqlInstanceDataSourceProperties has a subset of Cloud
    /// SQL Instance properties that are useful at the Datasource level.
    indirect case cloudSqlInstanceDatasourceProperties(CloudSqlInstanceDataSourceProperties)
    /// Output only. AlloyDBClusterDataSourceProperties has a subset of AlloyDB
    /// cluster properties that are useful at the Datasource level.
    indirect case alloyDbClusterDatasourceProperties(AlloyDBClusterDataSourceProperties)
    /// DiskDataSourceProperties has a subset of Disk properties that are useful
    /// at the Datasource level.
    indirect case diskDatasourceProperties(DiskDataSourceProperties)
  }

  /// The type URL for `DataSourceGcpResource`: `"type.googleapis.com/google.cloud.backupdr.v1.DataSourceGcpResource"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.DataSourceGcpResource"
  }

  /// Initialize an instance of `DataSourceGcpResource` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.DataSourceGcpResource"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DataSourceGcpResource` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
