// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// BackupApplianceApplication describes a Source Resource when it is an
/// application backed up by a BackupAppliance.
public struct DataSourceBackupApplianceApplication: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the Application as known to the Backup Appliance.
  public var applicationName: Swift.String = Swift.String()

  /// Appliance name.
  public var backupAppliance: Swift.String = Swift.String()

  /// Appliance Id of the Backup Appliance.
  public var applianceId: Swift.Int64 = Swift.Int64()

  /// The type of the application. e.g. VMBackup
  public var type: Swift.String = Swift.String()

  /// The appid field of the application within the Backup Appliance.
  public var applicationId: Swift.Int64 = Swift.Int64()

  /// Hostname of the host where the application is running.
  public var hostname: Swift.String = Swift.String()

  /// Hostid of the application host.
  public var hostId: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataSourceBackupApplianceApplication`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSourceBackupApplianceApplication().with { $0.applicationName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let applicationName = CodingKeys(stringValue: "applicationName")
    static let backupAppliance = CodingKeys(stringValue: "backupAppliance")
    static let applianceId = CodingKeys(stringValue: "applianceId")
    static let type = CodingKeys(stringValue: "type")
    static let applicationId = CodingKeys(stringValue: "applicationId")
    static let hostname = CodingKeys(stringValue: "hostname")
    static let hostId = CodingKeys(stringValue: "hostId")

    static let _knownKeys: Set<Swift.String> = [
      "applicationName",
      "backupAppliance",
      "applianceId",
      "type",
      "applicationId",
      "hostname",
      "hostId",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .applicationName) {
      self.applicationName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupAppliance) {
      self.backupAppliance = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .applianceId) {
      self.applianceId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .applicationId) {
      self.applicationId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostname) {
      self.hostname = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .hostId) {
      self.hostId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.applicationName, forKey: .applicationName)
    try container.encode(self.backupAppliance, forKey: .backupAppliance)
    try container.encode(self.applianceId, forKey: .applianceId)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.applicationId, forKey: .applicationId)
    try container.encode(self.hostname, forKey: .hostname)
    try container.encode(self.hostId, forKey: .hostId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `DataSourceBackupApplianceApplication`: `"type.googleapis.com/google.cloud.backupdr.v1.DataSourceBackupApplianceApplication"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.DataSourceBackupApplianceApplication"
  }

  /// Initialize an instance of `DataSourceBackupApplianceApplication` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.DataSourceBackupApplianceApplication"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DataSourceBackupApplianceApplication` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
