// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// DataSourceReference is a reference to a DataSource resource.
public struct DataSourceReference: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the DataSourceReference.
  /// Format:
  /// projects/{project}/locations/{location}/dataSourceReferences/{data_source_reference}
  public var name: Swift.String = Swift.String()

  /// Output only. The resource name of the DataSource.
  /// Format:
  /// projects/{project}/locations/{location}/backupVaults/{backupVault}/dataSources/{dataSource}
  public var dataSource: Swift.String = Swift.String()

  /// Output only. The time when the DataSourceReference was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The backup configuration state of the DataSource.
  public var dataSourceBackupConfigState: BackupConfigState = BackupConfigState()

  /// Output only. Number of backups in the DataSource.
  public var dataSourceBackupCount: Swift.Int64 = Swift.Int64()

  /// Output only. Information of backup configuration on the DataSource.
  public var dataSourceBackupConfigInfo: DataSourceBackupConfigInfo? = nil

  /// Output only. The GCP resource that the DataSource is associated with.
  public var dataSourceGcpResourceInfo: DataSourceGcpResourceInfo? = nil

  /// Output only. Total size of the storage used by all backup resources for the
  /// referenced datasource.
  public var totalStoredBytes: Swift.Int64? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataSourceReference`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSourceReference().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let dataSource = CodingKeys(stringValue: "dataSource")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let dataSourceBackupConfigState = CodingKeys(stringValue: "dataSourceBackupConfigState")
    static let dataSourceBackupCount = CodingKeys(stringValue: "dataSourceBackupCount")
    static let dataSourceBackupConfigInfo = CodingKeys(stringValue: "dataSourceBackupConfigInfo")
    static let dataSourceGcpResourceInfo = CodingKeys(stringValue: "dataSourceGcpResourceInfo")
    static let totalStoredBytes = CodingKeys(stringValue: "totalStoredBytes")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "dataSource",
      "createTime",
      "dataSourceBackupConfigState",
      "dataSourceBackupCount",
      "dataSourceBackupConfigInfo",
      "dataSourceGcpResourceInfo",
      "totalStoredBytes",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataSource) {
      self.dataSource = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(
      BackupConfigState.self, forKey: .dataSourceBackupConfigState)
    {
      self.dataSourceBackupConfigState = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .dataSourceBackupCount) {
      self.dataSourceBackupCount = value
    }
    self.dataSourceBackupConfigInfo = try container.decodeIfPresent(
      DataSourceBackupConfigInfo.self, forKey: .dataSourceBackupConfigInfo)
    self.dataSourceGcpResourceInfo = try container.decodeIfPresent(
      DataSourceGcpResourceInfo.self, forKey: .dataSourceGcpResourceInfo)
    self.totalStoredBytes = try container.decodeIfPresent(
      Swift.Int64.self, forKey: .totalStoredBytes)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.dataSource, forKey: .dataSource)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.dataSourceBackupConfigState, forKey: .dataSourceBackupConfigState)
    try container.encode(self.dataSourceBackupCount, forKey: .dataSourceBackupCount)
    try container.encodeIfPresent(
      self.dataSourceBackupConfigInfo, forKey: .dataSourceBackupConfigInfo)
    try container.encodeIfPresent(
      self.dataSourceGcpResourceInfo, forKey: .dataSourceGcpResourceInfo)
    try container.encodeIfPresent(self.totalStoredBytes, forKey: .totalStoredBytes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `DataSourceReference`: `"type.googleapis.com/google.cloud.backupdr.v1.DataSourceReference"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.DataSourceReference"
  }

  /// Initialize an instance of `DataSourceReference` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.DataSourceReference"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DataSourceReference` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
