// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The GCP resource that the DataSource is associated with.
public struct DataSourceGcpResourceInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the GCP resource.
  /// Ex: projects/{project}/zones/{zone}/instances/{instance}
  public var gcpResourcename: Swift.String = Swift.String()

  /// Output only. The type of the GCP resource.
  /// Ex: compute.googleapis.com/Instance
  public var type: Swift.String = Swift.String()

  /// Output only. The location of the GCP resource.
  /// Ex: <region>/<zone>/"global"/"unspecified"
  public var location: Swift.String = Swift.String()

  /// The properties of the GCP resource.
  public var resourceProperties: ResourcePropertiesOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataSourceGcpResourceInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataSourceGcpResourceInfo().with { $0.gcpResourcename = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcpResourcename = CodingKeys(stringValue: "gcpResourcename")
    static let type = CodingKeys(stringValue: "type")
    static let location = CodingKeys(stringValue: "location")
    static let cloudSqlInstanceProperties = CodingKeys(stringValue: "cloudSqlInstanceProperties")

    static let _knownKeys: Set<Swift.String> = [
      "gcpResourcename",
      "type",
      "location",
      "cloudSqlInstanceProperties",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gcpResourcename) {
      self.gcpResourcename = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
      self.location = value
    }

    var resourceProperties: ResourcePropertiesOneOf? = nil
    let resourcePropertiesCheckAndSet = {
      if resourceProperties != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'resourceProperties'"))
      }
      resourceProperties = $0
    }
    if let cloudSqlInstanceProperties = try container.decodeIfPresent(
      CloudSqlInstanceDataSourceReferenceProperties.self, forKey: .cloudSqlInstanceProperties)
    {
      try resourcePropertiesCheckAndSet(.cloudSqlInstanceProperties(cloudSqlInstanceProperties))
    }
    self.resourceProperties = resourceProperties
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.gcpResourcename, forKey: .gcpResourcename)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.location, forKey: .location)

    if let choice = self.resourceProperties {
      switch choice {
      case .cloudSqlInstanceProperties(let value):
        try container.encode(value, forKey: .cloudSqlInstanceProperties)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The properties of the GCP resource.
  public enum ResourcePropertiesOneOf: Codable, Equatable, Sendable {
    /// Output only. The properties of the Cloud SQL instance.
    indirect case cloudSqlInstanceProperties(CloudSqlInstanceDataSourceReferenceProperties)
  }

  /// The type URL for `DataSourceGcpResourceInfo`: `"type.googleapis.com/google.cloud.backupdr.v1.DataSourceGcpResourceInfo"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.DataSourceGcpResourceInfo"
  }

  /// Initialize an instance of `DataSourceGcpResourceInfo` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.DataSourceGcpResourceInfo"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DataSourceGcpResourceInfo` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
