// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// DiskBackupProperties represents the properties of a Disk backup.
public struct DiskBackupProperties: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A description of the source disk.
  public var description: Swift.String? = nil

  /// A list of publicly available licenses that are applicable to this backup.
  /// This is applicable if the original image had licenses attached, e.g.
  /// Windows image.
  public var licenses: [Swift.String] = []

  /// A list of guest OS features that are applicable to this backup.
  public var guestOsFeature: [GuestOsFeature] = []

  /// The architecture of the source disk. Valid values are
  /// ARM64 or X86_64.
  public var architecture: DiskBackupProperties.Architecture? = nil

  /// The URL of the type of the disk.
  public var type: Swift.String? = nil

  /// Size(in GB) of the source disk.
  public var sizeGb: Swift.Int64? = nil

  /// Region and zone are mutually exclusive fields.
  /// The URL of the region of the source disk.
  public var region: Swift.String? = nil

  /// The URL of the Zone where the source disk.
  public var zone: Swift.String? = nil

  /// The URL of the Zones where the source disk should be replicated.
  public var replicaZones: [Swift.String] = []

  /// The source disk used to create this backup.
  public var sourceDisk: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DiskBackupProperties`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiskBackupProperties().with { $0.description = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let description = CodingKeys(stringValue: "description")
    static let licenses = CodingKeys(stringValue: "licenses")
    static let guestOsFeature = CodingKeys(stringValue: "guestOsFeature")
    static let architecture = CodingKeys(stringValue: "architecture")
    static let type = CodingKeys(stringValue: "type")
    static let sizeGb = CodingKeys(stringValue: "sizeGb")
    static let region = CodingKeys(stringValue: "region")
    static let zone = CodingKeys(stringValue: "zone")
    static let replicaZones = CodingKeys(stringValue: "replicaZones")
    static let sourceDisk = CodingKeys(stringValue: "sourceDisk")

    static let _knownKeys: Set<Swift.String> = [
      "description",
      "licenses",
      "guestOsFeature",
      "architecture",
      "type",
      "sizeGb",
      "region",
      "zone",
      "replicaZones",
      "sourceDisk",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .licenses) {
      self.licenses = value
    }
    if let value = try container.decodeIfPresent([GuestOsFeature].self, forKey: .guestOsFeature) {
      self.guestOsFeature = value
    }
    self.architecture = try container.decodeIfPresent(
      DiskBackupProperties.Architecture.self, forKey: .architecture)
    self.type = try container.decodeIfPresent(Swift.String.self, forKey: .type)
    self.sizeGb = try container.decodeIfPresent(Swift.Int64.self, forKey: .sizeGb)
    self.region = try container.decodeIfPresent(Swift.String.self, forKey: .region)
    self.zone = try container.decodeIfPresent(Swift.String.self, forKey: .zone)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .replicaZones) {
      self.replicaZones = value
    }
    self.sourceDisk = try container.decodeIfPresent(Swift.String.self, forKey: .sourceDisk)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.description, forKey: .description)
    try container.encode(self.licenses, forKey: .licenses)
    try container.encode(self.guestOsFeature, forKey: .guestOsFeature)
    try container.encodeIfPresent(self.architecture, forKey: .architecture)
    try container.encodeIfPresent(self.type, forKey: .type)
    try container.encodeIfPresent(self.sizeGb, forKey: .sizeGb)
    try container.encodeIfPresent(self.region, forKey: .region)
    try container.encodeIfPresent(self.zone, forKey: .zone)
    try container.encode(self.replicaZones, forKey: .replicaZones)
    try container.encodeIfPresent(self.sourceDisk, forKey: .sourceDisk)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Architecture of the source disk.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Architecture: Codable, Equatable, Hashable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Disks with architecture X86_64
    case x8664
    /// Disks with architecture ARM64
    case arm64
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .x8664: return 1
      case .arm64: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ARCHITECTURE_UNSPECIFIED"
      case .x8664: return "X86_64"
      case .arm64: return "ARM64"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Architecture/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ARCHITECTURE_UNSPECIFIED": self = .unspecified
      case "X86_64": self = .x8664
      case "ARM64": self = .arm64
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Architecture/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .x8664
      case 2: self = .arm64
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ARCHITECTURE_UNSPECIFIED")
      case .x8664: return try container.encode("X86_64")
      case .arm64: return try container.encode("ARM64")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `DiskBackupProperties`: `"type.googleapis.com/google.cloud.backupdr.v1.DiskBackupProperties"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.DiskBackupProperties"
  }

  /// Initialize an instance of `DiskBackupProperties` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.DiskBackupProperties"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `DiskBackupProperties` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
