// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for the FetchBackupsForResourceType method.
public struct FetchBackupsForResourceTypeRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Datasources are the parent resource for the backups.
  /// Format:
  /// projects/{project}/locations/{location}/backupVaults/{backupVaultId}/dataSources/{datasourceId}
  public var parent: Swift.String = Swift.String()

  /// Required. The type of the GCP resource.
  /// Ex: sqladmin.googleapis.com/Instance
  public var resourceType: Swift.String = Swift.String()

  /// Optional. The maximum number of Backups to return. The service may
  /// return fewer than this value. If unspecified, at most 50
  /// Backups will be returned. The maximum value is 100; values
  /// above 100 will be coerced to 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous call of
  /// `FetchBackupsForResourceType`.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// `FetchBackupsForResourceType` must match
  /// the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A filter expression that filters the results fetched in the
  /// response. The expression must specify the field name, a comparison
  /// operator, and the value that you want to use for filtering. Supported
  /// fields:
  public var filter: Swift.String = Swift.String()

  /// Optional. A comma-separated list of fields to order by, sorted in ascending
  /// order. Use "desc" after a field name for descending.
  public var orderBy: Swift.String = Swift.String()

  /// Optional. This parameter is used to specify the view of the backup.
  /// If not specified, the default view is BASIC.
  public var view: BackupView = BackupView()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FetchBackupsForResourceTypeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FetchBackupsForResourceTypeRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let filter = CodingKeys(stringValue: "filter")
    static let orderBy = CodingKeys(stringValue: "orderBy")
    static let view = CodingKeys(stringValue: "view")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "resourceType",
      "pageSize",
      "pageToken",
      "filter",
      "orderBy",
      "view",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
      self.resourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .orderBy) {
      self.orderBy = value
    }
    if let value = try container.decodeIfPresent(BackupView.self, forKey: .view) {
      self.view = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.orderBy, forKey: .orderBy)
    try container.encode(self.view, forKey: .view)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `FetchBackupsForResourceTypeRequest`: `"type.googleapis.com/google.cloud.backupdr.v1.FetchBackupsForResourceTypeRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.FetchBackupsForResourceTypeRequest"
  }

  /// Initialize an instance of `FetchBackupsForResourceTypeRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.FetchBackupsForResourceTypeRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `FetchBackupsForResourceTypeRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
