// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Feature type of the Guest OS.
public struct GuestOsFeature: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The ID of a supported feature.
  public var type: GuestOsFeature.FeatureType? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GuestOsFeature`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GuestOsFeature().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "type")

    static let _knownKeys: Set<Swift.String> = [
      "type"
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.type = try container.decodeIfPresent(GuestOsFeature.FeatureType.self, forKey: .type)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.type, forKey: .type)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// List of the Feature Types.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum FeatureType: Codable, Equatable, Hashable, Sendable {
    /// Default value, which is unused.
    case unspecified
    /// VIRTIO_SCSI_MULTIQUEUE feature type.
    case virtioScsiMultiqueue
    /// WINDOWS feature type.
    case windows
    /// MULTI_IP_SUBNET feature type.
    case multiIpSubnet
    /// UEFI_COMPATIBLE feature type.
    case uefiCompatible
    /// SECURE_BOOT feature type.
    case secureBoot
    /// GVNIC feature type.
    case gvnic
    /// SEV_CAPABLE feature type.
    case sevCapable
    /// BARE_METAL_LINUX_COMPATIBLE feature type.
    case bareMetalLinuxCompatible
    /// SUSPEND_RESUME_COMPATIBLE feature type.
    case suspendResumeCompatible
    /// SEV_LIVE_MIGRATABLE feature type.
    case sevLiveMigratable
    /// SEV_SNP_CAPABLE feature type.
    case sevSnpCapable
    /// TDX_CAPABLE feature type.
    case tdxCapable
    /// IDPF feature type.
    case idpf
    /// SEV_LIVE_MIGRATABLE_V2 feature type.
    case sevLiveMigratableV2
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .virtioScsiMultiqueue: return 1
      case .windows: return 2
      case .multiIpSubnet: return 3
      case .uefiCompatible: return 4
      case .secureBoot: return 5
      case .gvnic: return 6
      case .sevCapable: return 7
      case .bareMetalLinuxCompatible: return 8
      case .suspendResumeCompatible: return 9
      case .sevLiveMigratable: return 10
      case .sevSnpCapable: return 11
      case .tdxCapable: return 12
      case .idpf: return 13
      case .sevLiveMigratableV2: return 14
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FEATURE_TYPE_UNSPECIFIED"
      case .virtioScsiMultiqueue: return "VIRTIO_SCSI_MULTIQUEUE"
      case .windows: return "WINDOWS"
      case .multiIpSubnet: return "MULTI_IP_SUBNET"
      case .uefiCompatible: return "UEFI_COMPATIBLE"
      case .secureBoot: return "SECURE_BOOT"
      case .gvnic: return "GVNIC"
      case .sevCapable: return "SEV_CAPABLE"
      case .bareMetalLinuxCompatible: return "BARE_METAL_LINUX_COMPATIBLE"
      case .suspendResumeCompatible: return "SUSPEND_RESUME_COMPATIBLE"
      case .sevLiveMigratable: return "SEV_LIVE_MIGRATABLE"
      case .sevSnpCapable: return "SEV_SNP_CAPABLE"
      case .tdxCapable: return "TDX_CAPABLE"
      case .idpf: return "IDPF"
      case .sevLiveMigratableV2: return "SEV_LIVE_MIGRATABLE_V2"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FeatureType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FEATURE_TYPE_UNSPECIFIED": self = .unspecified
      case "VIRTIO_SCSI_MULTIQUEUE": self = .virtioScsiMultiqueue
      case "WINDOWS": self = .windows
      case "MULTI_IP_SUBNET": self = .multiIpSubnet
      case "UEFI_COMPATIBLE": self = .uefiCompatible
      case "SECURE_BOOT": self = .secureBoot
      case "GVNIC": self = .gvnic
      case "SEV_CAPABLE": self = .sevCapable
      case "BARE_METAL_LINUX_COMPATIBLE": self = .bareMetalLinuxCompatible
      case "SUSPEND_RESUME_COMPATIBLE": self = .suspendResumeCompatible
      case "SEV_LIVE_MIGRATABLE": self = .sevLiveMigratable
      case "SEV_SNP_CAPABLE": self = .sevSnpCapable
      case "TDX_CAPABLE": self = .tdxCapable
      case "IDPF": self = .idpf
      case "SEV_LIVE_MIGRATABLE_V2": self = .sevLiveMigratableV2
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FeatureType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .virtioScsiMultiqueue
      case 2: self = .windows
      case 3: self = .multiIpSubnet
      case 4: self = .uefiCompatible
      case 5: self = .secureBoot
      case 6: self = .gvnic
      case 7: self = .sevCapable
      case 8: self = .bareMetalLinuxCompatible
      case 9: self = .suspendResumeCompatible
      case 10: self = .sevLiveMigratable
      case 11: self = .sevSnpCapable
      case 12: self = .tdxCapable
      case 13: self = .idpf
      case 14: self = .sevLiveMigratableV2
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("FEATURE_TYPE_UNSPECIFIED")
      case .virtioScsiMultiqueue: return try container.encode("VIRTIO_SCSI_MULTIQUEUE")
      case .windows: return try container.encode("WINDOWS")
      case .multiIpSubnet: return try container.encode("MULTI_IP_SUBNET")
      case .uefiCompatible: return try container.encode("UEFI_COMPATIBLE")
      case .secureBoot: return try container.encode("SECURE_BOOT")
      case .gvnic: return try container.encode("GVNIC")
      case .sevCapable: return try container.encode("SEV_CAPABLE")
      case .bareMetalLinuxCompatible: return try container.encode("BARE_METAL_LINUX_COMPATIBLE")
      case .suspendResumeCompatible: return try container.encode("SUSPEND_RESUME_COMPATIBLE")
      case .sevLiveMigratable: return try container.encode("SEV_LIVE_MIGRATABLE")
      case .sevSnpCapable: return try container.encode("SEV_SNP_CAPABLE")
      case .tdxCapable: return try container.encode("TDX_CAPABLE")
      case .idpf: return try container.encode("IDPF")
      case .sevLiveMigratableV2: return try container.encode("SEV_LIVE_MIGRATABLE_V2")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `GuestOsFeature`: `"type.googleapis.com/google.cloud.backupdr.v1.GuestOsFeature"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.GuestOsFeature"
  }

  /// Initialize an instance of `GuestOsFeature` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.GuestOsFeature"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `GuestOsFeature` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
