// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for initializing the service.
public struct InitializeServiceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the serviceConfig used to initialize the
  /// service. Format:
  /// `projects/{project_id}/locations/{location}/serviceConfig`.
  public var name: Swift.String = Swift.String()

  /// Required. The resource type to which the default service config will be
  /// applied. Examples include, "compute.googleapis.com/Instance" and
  /// "storage.googleapis.com/Bucket".
  public var resourceType: Swift.String = Swift.String()

  /// Optional. An optional request ID to identify requests. Specify a unique
  /// request ID so that if you must retry your request, the server will know to
  /// ignore the request if it has already been completed. The server will
  /// guarantee that for at least 60 minutes since the first request.
  ///
  /// For example, consider a situation where you make an initial request and t
  /// he request times out. If you make the request again with the same request
  /// ID, the server can check if original operation with the same request ID
  /// was received, and if so, will ignore the second request. This prevents
  /// clients from accidentally creating duplicate commitments.
  ///
  /// The request ID must be a valid UUID with the exception that zero UUID is
  /// not supported (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// The configuration for initializing the resource.
  public var initializationConfig: InitializationConfigOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InitializeServiceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InitializeServiceRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let resourceType = CodingKeys(stringValue: "resourceType")
    static let requestId = CodingKeys(stringValue: "requestId")
    static let cloudSqlInstanceInitializationConfig = CodingKeys(
      stringValue: "cloudSqlInstanceInitializationConfig")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "resourceType",
      "requestId",
      "cloudSqlInstanceInitializationConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
      self.resourceType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }

    var initializationConfig: InitializationConfigOneOf? = nil
    let initializationConfigCheckAndSet = {
      if initializationConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'initializationConfig'"))
      }
      initializationConfig = $0
    }
    if let cloudSqlInstanceInitializationConfig = try container.decodeIfPresent(
      CloudSqlInstanceInitializationConfig.self, forKey: .cloudSqlInstanceInitializationConfig)
    {
      try initializationConfigCheckAndSet(
        .cloudSqlInstanceInitializationConfig(cloudSqlInstanceInitializationConfig))
    }
    self.initializationConfig = initializationConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.resourceType, forKey: .resourceType)
    try container.encode(self.requestId, forKey: .requestId)

    if let choice = self.initializationConfig {
      switch choice {
      case .cloudSqlInstanceInitializationConfig(let value):
        try container.encode(value, forKey: .cloudSqlInstanceInitializationConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The configuration for initializing the resource.
  public enum InitializationConfigOneOf: Codable, Equatable, Sendable {
    /// Optional. The configuration for initializing a Cloud SQL instance.
    indirect case cloudSqlInstanceInitializationConfig(CloudSqlInstanceInitializationConfig)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.InitializeServiceRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
