// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleGax
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The response message for getting a list of `BackupPlan`.
public struct ListBackupPlansResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The list of `BackupPlans` in the project for the specified
  /// location.
  ///
  /// If the `{location}` value in the request is "-", the response contains a
  /// list of resources from all locations. In case any location is unreachable,
  /// the response will only return backup plans in reachable locations and
  /// the 'unreachable' field will be populated with a list of unreachable
  /// locations.
  /// BackupPlan
  public var backupPlans: [BackupPlan] = []

  /// A token which may be sent as
  /// [page_token][google.cloud.backupdr.v1.ListBackupPlansRequest.page_token] in
  /// a subsequent `ListBackupPlans` call to retrieve the next page of results.
  /// If this field is omitted or empty, then there are no more results to
  /// return.
  ///
  /// [google.cloud.backupdr.v1.ListBackupPlansRequest.page_token]: <doc:ListBackupPlansRequest/pageToken>
  public var nextPageToken: Swift.String = Swift.String()

  /// Locations that could not be reached.
  public var unreachable: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListBackupPlansResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListBackupPlansResponse().with { $0.backupPlans = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let backupPlans = CodingKeys(stringValue: "backupPlans")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let unreachable = CodingKeys(stringValue: "unreachable")

    static let _knownKeys: Set<Swift.String> = [
      "backupPlans",
      "nextPageToken",
      "unreachable",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([BackupPlan].self, forKey: .backupPlans) {
      self.backupPlans = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .unreachable) {
      self.unreachable = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.backupPlans, forKey: .backupPlans)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.unreachable, forKey: .unreachable)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ListBackupPlansResponse`: `"type.googleapis.com/google.cloud.backupdr.v1.ListBackupPlansResponse"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.ListBackupPlansResponse"
  }

  /// Initialize an instance of `ListBackupPlansResponse` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.ListBackupPlansResponse"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ListBackupPlansResponse` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension ListBackupPlansResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [BackupPlan] {
    return self.backupPlans
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
