// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A network interface resource attached to an instance.
/// s
public struct NetworkInterface: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. URL of the VPC network resource for this instance.
  public var network: Swift.String? = nil

  /// Optional. The URL of the Subnetwork resource for this instance.
  public var subnetwork: Swift.String? = nil

  /// Optional. An IPv4 internal IP address to assign to the instance for this
  /// network interface. If not specified by the user, an unused internal IP is
  /// assigned by the system.
  public var ipAddress: Swift.String? = nil

  /// Optional. An IPv6 internal network address for this network interface. To
  /// use a static internal IP address, it must be unused and in the same region
  /// as the instance's zone. If not specified, Google Cloud will automatically
  /// assign an internal IPv6 address from the instance's subnetwork.
  public var ipv6Address: Swift.String? = nil

  /// Optional. The prefix length of the primary internal IPv6 range.
  public var internalIpv6PrefixLength: Swift.Int32? = nil

  /// Output only. [Output Only] The name of the network interface, which is
  /// generated by the server.
  public var name: Swift.String? = nil

  /// Optional. An array of configurations for this interface. Currently, only
  /// one access config,ONE_TO_ONE_NAT is supported. If there are no
  /// accessConfigs specified, then this instance will have
  /// no external internet access.
  public var accessConfigs: [AccessConfig] = []

  /// Optional. An array of IPv6 access configurations for this interface.
  /// Currently, only one IPv6 access config, DIRECT_IPV6, is supported. If there
  /// is no ipv6AccessConfig specified, then this instance will
  /// have no external IPv6 Internet access.
  public var ipv6AccessConfigs: [AccessConfig] = []

  /// Optional. An array of alias IP ranges for this network interface.
  /// You can only specify this field for network interfaces in VPC networks.
  public var aliasIpRanges: [AliasIpRange] = []

  /// The stack type for this network interface.
  public var stackType: NetworkInterface.StackType? = nil

  /// Optional. [Output Only] One of EXTERNAL, INTERNAL to indicate whether the
  /// IP can be accessed from the Internet. This field is always inherited from
  /// its subnetwork.
  public var ipv6AccessType: NetworkInterface.Ipv6AccessType? = nil

  /// Optional. The networking queue count that's specified by users for the
  /// network interface. Both Rx and Tx queues will be set to this number. It'll
  /// be empty if not specified by the users.
  public var queueCount: Swift.Int32? = nil

  /// Optional. The type of vNIC to be used on this interface. This may be gVNIC
  /// or VirtioNet.
  public var nicType: NetworkInterface.NicType? = nil

  /// Optional. The URL of the network attachment that this interface should
  /// connect to in the following format:
  /// projects/{project_number}/regions/{region_name}/networkAttachments/{network_attachment_name}.
  public var networkAttachment: Swift.String? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NetworkInterface`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NetworkInterface().with { $0.network = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let network = CodingKeys(stringValue: "network")
    static let subnetwork = CodingKeys(stringValue: "subnetwork")
    static let ipAddress = CodingKeys(stringValue: "networkIP")
    static let ipv6Address = CodingKeys(stringValue: "ipv6Address")
    static let internalIpv6PrefixLength = CodingKeys(stringValue: "internalIpv6PrefixLength")
    static let name = CodingKeys(stringValue: "name")
    static let accessConfigs = CodingKeys(stringValue: "accessConfigs")
    static let ipv6AccessConfigs = CodingKeys(stringValue: "ipv6AccessConfigs")
    static let aliasIpRanges = CodingKeys(stringValue: "aliasIpRanges")
    static let stackType = CodingKeys(stringValue: "stackType")
    static let ipv6AccessType = CodingKeys(stringValue: "ipv6AccessType")
    static let queueCount = CodingKeys(stringValue: "queueCount")
    static let nicType = CodingKeys(stringValue: "nicType")
    static let networkAttachment = CodingKeys(stringValue: "networkAttachment")

    static let _knownKeys: Set<Swift.String> = [
      "network",
      "subnetwork",
      "networkIP",
      "ipv6Address",
      "internalIpv6PrefixLength",
      "name",
      "accessConfigs",
      "ipv6AccessConfigs",
      "aliasIpRanges",
      "stackType",
      "ipv6AccessType",
      "queueCount",
      "nicType",
      "networkAttachment",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.network = try container.decodeIfPresent(Swift.String.self, forKey: .network)
    self.subnetwork = try container.decodeIfPresent(Swift.String.self, forKey: .subnetwork)
    self.ipAddress = try container.decodeIfPresent(Swift.String.self, forKey: .ipAddress)
    self.ipv6Address = try container.decodeIfPresent(Swift.String.self, forKey: .ipv6Address)
    self.internalIpv6PrefixLength = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .internalIpv6PrefixLength)
    self.name = try container.decodeIfPresent(Swift.String.self, forKey: .name)
    if let value = try container.decodeIfPresent([AccessConfig].self, forKey: .accessConfigs) {
      self.accessConfigs = value
    }
    if let value = try container.decodeIfPresent([AccessConfig].self, forKey: .ipv6AccessConfigs) {
      self.ipv6AccessConfigs = value
    }
    if let value = try container.decodeIfPresent([AliasIpRange].self, forKey: .aliasIpRanges) {
      self.aliasIpRanges = value
    }
    self.stackType = try container.decodeIfPresent(
      NetworkInterface.StackType.self, forKey: .stackType)
    self.ipv6AccessType = try container.decodeIfPresent(
      NetworkInterface.Ipv6AccessType.self, forKey: .ipv6AccessType)
    self.queueCount = try container.decodeIfPresent(Swift.Int32.self, forKey: .queueCount)
    self.nicType = try container.decodeIfPresent(NetworkInterface.NicType.self, forKey: .nicType)
    self.networkAttachment = try container.decodeIfPresent(
      Swift.String.self, forKey: .networkAttachment)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.network, forKey: .network)
    try container.encodeIfPresent(self.subnetwork, forKey: .subnetwork)
    try container.encodeIfPresent(self.ipAddress, forKey: .ipAddress)
    try container.encodeIfPresent(self.ipv6Address, forKey: .ipv6Address)
    try container.encodeIfPresent(self.internalIpv6PrefixLength, forKey: .internalIpv6PrefixLength)
    try container.encodeIfPresent(self.name, forKey: .name)
    try container.encode(self.accessConfigs, forKey: .accessConfigs)
    try container.encode(self.ipv6AccessConfigs, forKey: .ipv6AccessConfigs)
    try container.encode(self.aliasIpRanges, forKey: .aliasIpRanges)
    try container.encodeIfPresent(self.stackType, forKey: .stackType)
    try container.encodeIfPresent(self.ipv6AccessType, forKey: .ipv6AccessType)
    try container.encodeIfPresent(self.queueCount, forKey: .queueCount)
    try container.encodeIfPresent(self.nicType, forKey: .nicType)
    try container.encodeIfPresent(self.networkAttachment, forKey: .networkAttachment)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Stack type for this network interface.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum StackType: Codable, Equatable, Hashable, Sendable {
    /// Default should be STACK_TYPE_UNSPECIFIED.
    case unspecified
    /// The network interface will be assigned IPv4 address.
    case ipv4Only
    /// The network interface can have both IPv4 and IPv6 addresses.
    case ipv4Ipv6
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ipv4Only: return 1
      case .ipv4Ipv6: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STACK_TYPE_UNSPECIFIED"
      case .ipv4Only: return "IPV4_ONLY"
      case .ipv4Ipv6: return "IPV4_IPV6"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:StackType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STACK_TYPE_UNSPECIFIED": self = .unspecified
      case "IPV4_ONLY": self = .ipv4Only
      case "IPV4_IPV6": self = .ipv4Ipv6
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:StackType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ipv4Only
      case 2: self = .ipv4Ipv6
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STACK_TYPE_UNSPECIFIED")
      case .ipv4Only: return try container.encode("IPV4_ONLY")
      case .ipv4Ipv6: return try container.encode("IPV4_IPV6")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// IPv6 access type for this network interface.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Ipv6AccessType: Codable, Equatable, Hashable, Sendable {
    /// IPv6 access type not set. Means this network interface hasn't been
    /// turned on IPv6 yet.
    case unspecifiedIpv6AccessType
    /// This network interface can have internal IPv6.
    case `internal`
    /// This network interface can have external IPv6.
    case external
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecifiedIpv6AccessType
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecifiedIpv6AccessType: return 0
      case .`internal`: return 1
      case .external: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecifiedIpv6AccessType: return "UNSPECIFIED_IPV6_ACCESS_TYPE"
      case .`internal`: return "INTERNAL"
      case .external: return "EXTERNAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Ipv6AccessType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED_IPV6_ACCESS_TYPE": self = .unspecifiedIpv6AccessType
      case "INTERNAL": self = .`internal`
      case "EXTERNAL": self = .external
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Ipv6AccessType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecifiedIpv6AccessType
      case 1: self = .`internal`
      case 2: self = .external
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecifiedIpv6AccessType: return try container.encode("UNSPECIFIED_IPV6_ACCESS_TYPE")
      case .`internal`: return try container.encode("INTERNAL")
      case .external: return try container.encode("EXTERNAL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Nic type for this network interface.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum NicType: Codable, Equatable, Hashable, Sendable {
    /// Default should be NIC_TYPE_UNSPECIFIED.
    case unspecified
    /// VIRTIO
    case virtioNet
    /// GVNIC
    case gvnic
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .virtioNet: return 1
      case .gvnic: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "NIC_TYPE_UNSPECIFIED"
      case .virtioNet: return "VIRTIO_NET"
      case .gvnic: return "GVNIC"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NicType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "NIC_TYPE_UNSPECIFIED": self = .unspecified
      case "VIRTIO_NET": self = .virtioNet
      case "GVNIC": self = .gvnic
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NicType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .virtioNet
      case 2: self = .gvnic
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("NIC_TYPE_UNSPECIFIED")
      case .virtioNet: return try container.encode("VIRTIO_NET")
      case .gvnic: return try container.encode("GVNIC")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `NetworkInterface`: `"type.googleapis.com/google.cloud.backupdr.v1.NetworkInterface"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.NetworkInterface"
  }

  /// Initialize an instance of `NetworkInterface` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.NetworkInterface"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `NetworkInterface` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
