// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for restoring from a Backup.
public struct RestoreBackupRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the Backup instance, in the format
  /// 'projects/*/locations/*/backupVaults/*/dataSources/*/backups/'.
  public var name: Swift.String = Swift.String()

  /// Optional. An optional request ID to identify requests. Specify a unique
  /// request ID so that if you must retry your request, the server will know to
  /// ignore the request if it has already been completed. The server will
  /// guarantee that for at least 60 minutes after the first request.
  ///
  /// For example, consider a situation where you make an initial request and
  /// the request times out. If you make the request again with the same request
  /// ID, the server can check if original operation with the same request ID
  /// was received, and if so, will ignore the second request. This prevents
  /// clients from accidentally creating duplicate commitments.
  ///
  /// The request ID must be a valid UUID with the exception that zero UUID is
  /// not supported (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Optional. A field mask used to clear server-side default values
  /// for fields within the `instance_properties` oneof.
  ///
  /// When a field in this mask is cleared, the server will not apply its
  /// default logic (like inheriting a value from the source) for that field.
  ///
  /// The most common current use case is clearing default encryption keys.
  ///
  /// Examples of field mask paths:
  /// - Compute Instance Disks:
  /// `compute_instance_restore_properties.disks.*.disk_encryption_key`
  /// - Single Disk: `disk_restore_properties.disk_encryption_key`
  public var clearOverridesFieldMask: GoogleWKT.WKTFieldMask? = nil

  /// The target environment for the restore operation.
  public var targetEnvironment: TargetEnvironmentOneOf? = nil

  /// The property overrides for the instance being restored.
  public var instanceProperties: InstancePropertiesOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RestoreBackupRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestoreBackupRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let requestId = CodingKeys(stringValue: "requestId")
    static let computeInstanceTargetEnvironment = CodingKeys(
      stringValue: "computeInstanceTargetEnvironment")
    static let diskTargetEnvironment = CodingKeys(stringValue: "diskTargetEnvironment")
    static let regionDiskTargetEnvironment = CodingKeys(stringValue: "regionDiskTargetEnvironment")
    static let computeInstanceRestoreProperties = CodingKeys(
      stringValue: "computeInstanceRestoreProperties")
    static let diskRestoreProperties = CodingKeys(stringValue: "diskRestoreProperties")
    static let clearOverridesFieldMask = CodingKeys(stringValue: "clearOverridesFieldMask")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "requestId",
      "computeInstanceTargetEnvironment",
      "diskTargetEnvironment",
      "regionDiskTargetEnvironment",
      "computeInstanceRestoreProperties",
      "diskRestoreProperties",
      "clearOverridesFieldMask",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    self.clearOverridesFieldMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .clearOverridesFieldMask)

    var targetEnvironment: TargetEnvironmentOneOf? = nil
    let targetEnvironmentCheckAndSet = {
      if targetEnvironment != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'targetEnvironment'"))
      }
      targetEnvironment = $0
    }
    if let computeInstanceTargetEnvironment = try container.decodeIfPresent(
      ComputeInstanceTargetEnvironment.self, forKey: .computeInstanceTargetEnvironment)
    {
      try targetEnvironmentCheckAndSet(
        .computeInstanceTargetEnvironment(computeInstanceTargetEnvironment))
    }
    if let diskTargetEnvironment = try container.decodeIfPresent(
      DiskTargetEnvironment.self, forKey: .diskTargetEnvironment)
    {
      try targetEnvironmentCheckAndSet(.diskTargetEnvironment(diskTargetEnvironment))
    }
    if let regionDiskTargetEnvironment = try container.decodeIfPresent(
      RegionDiskTargetEnvironment.self, forKey: .regionDiskTargetEnvironment)
    {
      try targetEnvironmentCheckAndSet(.regionDiskTargetEnvironment(regionDiskTargetEnvironment))
    }
    self.targetEnvironment = targetEnvironment

    var instanceProperties: InstancePropertiesOneOf? = nil
    let instancePropertiesCheckAndSet = {
      if instanceProperties != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'instanceProperties'"))
      }
      instanceProperties = $0
    }
    if let computeInstanceRestoreProperties = try container.decodeIfPresent(
      ComputeInstanceRestoreProperties.self, forKey: .computeInstanceRestoreProperties)
    {
      try instancePropertiesCheckAndSet(
        .computeInstanceRestoreProperties(computeInstanceRestoreProperties))
    }
    if let diskRestoreProperties = try container.decodeIfPresent(
      DiskRestoreProperties.self, forKey: .diskRestoreProperties)
    {
      try instancePropertiesCheckAndSet(.diskRestoreProperties(diskRestoreProperties))
    }
    self.instanceProperties = instanceProperties
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.requestId, forKey: .requestId)
    try container.encodeIfPresent(self.clearOverridesFieldMask, forKey: .clearOverridesFieldMask)

    if let choice = self.targetEnvironment {
      switch choice {
      case .computeInstanceTargetEnvironment(let value):
        try container.encode(value, forKey: .computeInstanceTargetEnvironment)
      case .diskTargetEnvironment(let value):
        try container.encode(value, forKey: .diskTargetEnvironment)
      case .regionDiskTargetEnvironment(let value):
        try container.encode(value, forKey: .regionDiskTargetEnvironment)
      }
    }

    if let choice = self.instanceProperties {
      switch choice {
      case .computeInstanceRestoreProperties(let value):
        try container.encode(value, forKey: .computeInstanceRestoreProperties)
      case .diskRestoreProperties(let value):
        try container.encode(value, forKey: .diskRestoreProperties)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The target environment for the restore operation.
  public enum TargetEnvironmentOneOf: Codable, Equatable, Sendable {
    /// Compute Engine target environment to be used during restore.
    indirect case computeInstanceTargetEnvironment(ComputeInstanceTargetEnvironment)
    /// Disk target environment to be used during restore.
    indirect case diskTargetEnvironment(DiskTargetEnvironment)
    /// Region disk target environment to be used during restore.
    indirect case regionDiskTargetEnvironment(RegionDiskTargetEnvironment)
  }

  /// The property overrides for the instance being restored.
  public enum InstancePropertiesOneOf: Codable, Equatable, Sendable {
    /// Compute Engine instance properties to be overridden during restore.
    indirect case computeInstanceRestoreProperties(ComputeInstanceRestoreProperties)
    /// Disk properties to be overridden during restore.
    indirect case diskRestoreProperties(DiskRestoreProperties)
  }

  /// The type URL for `RestoreBackupRequest`: `"type.googleapis.com/google.cloud.backupdr.v1.RestoreBackupRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.RestoreBackupRequest"
  }

  /// Initialize an instance of `RestoreBackupRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.RestoreBackupRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `RestoreBackupRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
