// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message for rules config info.
public struct RuleConfigInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Backup Rule id fetched from backup plan.
  public var ruleId: Swift.String = Swift.String()

  /// Output only. The last backup state for rule.
  public var lastBackupState: RuleConfigInfo.LastBackupState = RuleConfigInfo.LastBackupState()

  /// Output only. google.rpc.Status object to store the last backup error.
  public var lastBackupError: GoogleRpc.Status? = nil

  /// Output only. The point in time when the last successful backup was captured
  /// from the source.
  public var lastSuccessfulBackupConsistencyTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RuleConfigInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuleConfigInfo().with { $0.ruleId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ruleId = CodingKeys(stringValue: "ruleId")
    static let lastBackupState = CodingKeys(stringValue: "lastBackupState")
    static let lastBackupError = CodingKeys(stringValue: "lastBackupError")
    static let lastSuccessfulBackupConsistencyTime = CodingKeys(
      stringValue: "lastSuccessfulBackupConsistencyTime")

    static let _knownKeys: Set<Swift.String> = [
      "ruleId",
      "lastBackupState",
      "lastBackupError",
      "lastSuccessfulBackupConsistencyTime",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ruleId) {
      self.ruleId = value
    }
    if let value = try container.decodeIfPresent(
      RuleConfigInfo.LastBackupState.self, forKey: .lastBackupState)
    {
      self.lastBackupState = value
    }
    self.lastBackupError = try container.decodeIfPresent(
      GoogleRpc.Status.self, forKey: .lastBackupError)
    self.lastSuccessfulBackupConsistencyTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastSuccessfulBackupConsistencyTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ruleId, forKey: .ruleId)
    try container.encode(self.lastBackupState, forKey: .lastBackupState)
    try container.encodeIfPresent(self.lastBackupError, forKey: .lastBackupError)
    try container.encodeIfPresent(
      self.lastSuccessfulBackupConsistencyTime, forKey: .lastSuccessfulBackupConsistencyTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Enum for LastBackupState
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum LastBackupState: Codable, Equatable, Hashable, Sendable {
    /// State not set.
    case unspecified
    /// The first backup is pending.
    case firstBackupPending
    /// The most recent backup could not be run/failed because of the lack of
    /// permissions.
    case permissionDenied
    /// The last backup operation succeeded.
    case succeeded
    /// The last backup operation failed.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .firstBackupPending: return 1
      case .permissionDenied: return 2
      case .succeeded: return 3
      case .failed: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "LAST_BACKUP_STATE_UNSPECIFIED"
      case .firstBackupPending: return "FIRST_BACKUP_PENDING"
      case .permissionDenied: return "PERMISSION_DENIED"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LastBackupState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LAST_BACKUP_STATE_UNSPECIFIED": self = .unspecified
      case "FIRST_BACKUP_PENDING": self = .firstBackupPending
      case "PERMISSION_DENIED": self = .permissionDenied
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LastBackupState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .firstBackupPending
      case 2: self = .permissionDenied
      case 3: self = .succeeded
      case 4: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("LAST_BACKUP_STATE_UNSPECIFIED")
      case .firstBackupPending: return try container.encode("FIRST_BACKUP_PENDING")
      case .permissionDenied: return try container.encode("PERMISSION_DENIED")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .failed: return try container.encode("FAILED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `RuleConfigInfo`: `"type.googleapis.com/google.cloud.backupdr.v1.RuleConfigInfo"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.RuleConfigInfo"
  }

  /// Initialize an instance of `RuleConfigInfo` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.RuleConfigInfo"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `RuleConfigInfo` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
