// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Sets the scheduling options for an Instance.
public struct Scheduling: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Defines the maintenance behavior for this instance.
  public var onHostMaintenance: Scheduling.OnHostMaintenance? = nil

  /// Optional. Specifies whether the instance should be automatically restarted
  /// if it is terminated by Compute Engine (not terminated by a user).
  public var automaticRestart: Swift.Bool? = nil

  /// Optional. Defines whether the instance is preemptible.
  public var preemptible: Swift.Bool? = nil

  /// Optional. A set of node affinity and anti-affinity configurations.
  /// Overrides reservationAffinity.
  public var nodeAffinities: [Scheduling.NodeAffinity] = []

  /// Optional. The minimum number of virtual CPUs this instance will consume
  /// when running on a sole-tenant node.
  public var minNodeCpus: Swift.Int32? = nil

  /// Optional. Specifies the provisioning model of the instance.
  public var provisioningModel: Scheduling.ProvisioningModel? = nil

  /// Optional. Specifies the termination action for the instance.
  public var instanceTerminationAction: Scheduling.InstanceTerminationAction? = nil

  /// Optional. Specifies the maximum amount of time a Local Ssd Vm should wait
  /// while recovery of the Local Ssd state is attempted. Its value should be in
  /// between 0 and 168 hours with hour granularity and the default value being 1
  /// hour.
  public var localSsdRecoveryTimeout: SchedulingDuration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Scheduling`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Scheduling().with { $0.onHostMaintenance = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let onHostMaintenance = CodingKeys(stringValue: "onHostMaintenance")
    static let automaticRestart = CodingKeys(stringValue: "automaticRestart")
    static let preemptible = CodingKeys(stringValue: "preemptible")
    static let nodeAffinities = CodingKeys(stringValue: "nodeAffinities")
    static let minNodeCpus = CodingKeys(stringValue: "minNodeCpus")
    static let provisioningModel = CodingKeys(stringValue: "provisioningModel")
    static let instanceTerminationAction = CodingKeys(stringValue: "instanceTerminationAction")
    static let localSsdRecoveryTimeout = CodingKeys(stringValue: "localSsdRecoveryTimeout")

    static let _knownKeys: Set<Swift.String> = [
      "onHostMaintenance",
      "automaticRestart",
      "preemptible",
      "nodeAffinities",
      "minNodeCpus",
      "provisioningModel",
      "instanceTerminationAction",
      "localSsdRecoveryTimeout",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.onHostMaintenance = try container.decodeIfPresent(
      Scheduling.OnHostMaintenance.self, forKey: .onHostMaintenance)
    self.automaticRestart = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .automaticRestart)
    self.preemptible = try container.decodeIfPresent(Swift.Bool.self, forKey: .preemptible)
    if let value = try container.decodeIfPresent(
      [Scheduling.NodeAffinity].self, forKey: .nodeAffinities)
    {
      self.nodeAffinities = value
    }
    self.minNodeCpus = try container.decodeIfPresent(Swift.Int32.self, forKey: .minNodeCpus)
    self.provisioningModel = try container.decodeIfPresent(
      Scheduling.ProvisioningModel.self, forKey: .provisioningModel)
    self.instanceTerminationAction = try container.decodeIfPresent(
      Scheduling.InstanceTerminationAction.self, forKey: .instanceTerminationAction)
    self.localSsdRecoveryTimeout = try container.decodeIfPresent(
      SchedulingDuration.self, forKey: .localSsdRecoveryTimeout)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.onHostMaintenance, forKey: .onHostMaintenance)
    try container.encodeIfPresent(self.automaticRestart, forKey: .automaticRestart)
    try container.encodeIfPresent(self.preemptible, forKey: .preemptible)
    try container.encode(self.nodeAffinities, forKey: .nodeAffinities)
    try container.encodeIfPresent(self.minNodeCpus, forKey: .minNodeCpus)
    try container.encodeIfPresent(self.provisioningModel, forKey: .provisioningModel)
    try container.encodeIfPresent(
      self.instanceTerminationAction, forKey: .instanceTerminationAction)
    try container.encodeIfPresent(self.localSsdRecoveryTimeout, forKey: .localSsdRecoveryTimeout)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Node Affinity: the configuration of desired nodes onto which this Instance
  /// could be scheduled.
  public struct NodeAffinity: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Corresponds to the label key of Node resource.
    public var key: Swift.String? = nil

    /// Optional. Defines the operation of node selection.
    public var `operator`: Scheduling.NodeAffinity.Operator? = nil

    /// Optional. Corresponds to the label values of Node resource.
    public var values: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NodeAffinity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NodeAffinity().with { $0.key = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let key = CodingKeys(stringValue: "key")
      static let `operator` = CodingKeys(stringValue: "operator")
      static let values = CodingKeys(stringValue: "values")

      static let _knownKeys: Set<Swift.String> = [
        "key",
        "operator",
        "values",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.key = try container.decodeIfPresent(Swift.String.self, forKey: .key)
      self.`operator` = try container.decodeIfPresent(
        Scheduling.NodeAffinity.Operator.self, forKey: .`operator`)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .values) {
        self.values = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.key, forKey: .key)
      try container.encodeIfPresent(self.`operator`, forKey: .`operator`)
      try container.encode(self.values, forKey: .values)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Defines the type of node selections.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum Operator: Codable, Equatable, Hashable, Sendable {
      /// Default value. This value is unused.
      case unspecified
      /// Requires Compute Engine to seek for matched nodes.
      case `in`
      /// Requires Compute Engine to avoid certain nodes.
      case notIn
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .`in`: return 1
        case .notIn: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "OPERATOR_UNSPECIFIED"
        case .`in`: return "IN"
        case .notIn: return "NOT_IN"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Operator/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "OPERATOR_UNSPECIFIED": self = .unspecified
        case "IN": self = .`in`
        case "NOT_IN": self = .notIn
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Operator/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .`in`
        case 2: self = .notIn
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("OPERATOR_UNSPECIFIED")
        case .`in`: return try container.encode("IN")
        case .notIn: return try container.encode("NOT_IN")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The type URL for `NodeAffinity`: `"type.googleapis.com/google.cloud.backupdr.v1.Scheduling.NodeAffinity"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.backupdr.v1.Scheduling.NodeAffinity"
    }

    /// Initialize an instance of `NodeAffinity` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.Scheduling.NodeAffinity"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `NodeAffinity` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines the maintenance behavior for this instance=
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum OnHostMaintenance: Codable, Equatable, Hashable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Tells Compute Engine to terminate and (optionally) restart the instance
    /// away from the maintenance activity.
    case terminate
    /// Default, Allows Compute Engine to automatically migrate instances
    /// out of the way of maintenance events.
    case migrate
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .terminate: return 1
      case .migrate: return 1000
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ON_HOST_MAINTENANCE_UNSPECIFIED"
      case .terminate: return "TERMINATE"
      case .migrate: return "MIGRATE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OnHostMaintenance/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ON_HOST_MAINTENANCE_UNSPECIFIED": self = .unspecified
      case "TERMINATE": self = .terminate
      case "MIGRATE": self = .migrate
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OnHostMaintenance/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .terminate
      case 1000: self = .migrate
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("ON_HOST_MAINTENANCE_UNSPECIFIED")
      case .terminate: return try container.encode("TERMINATE")
      case .migrate: return try container.encode("MIGRATE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Defines the provisioning model for an instance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ProvisioningModel: Codable, Equatable, Hashable, Sendable {
    /// Default value. This value is not used.
    case unspecified
    /// Standard provisioning with user controlled runtime, no discounts.
    case standard
    /// Heavily discounted, no guaranteed runtime.
    case spot
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .standard: return 1
      case .spot: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROVISIONING_MODEL_UNSPECIFIED"
      case .standard: return "STANDARD"
      case .spot: return "SPOT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ProvisioningModel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROVISIONING_MODEL_UNSPECIFIED": self = .unspecified
      case "STANDARD": self = .standard
      case "SPOT": self = .spot
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ProvisioningModel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .standard
      case 2: self = .spot
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PROVISIONING_MODEL_UNSPECIFIED")
      case .standard: return try container.encode("STANDARD")
      case .spot: return try container.encode("SPOT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Defines the supported termination actions for an instance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum InstanceTerminationAction: Codable, Equatable, Hashable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Delete the VM.
    case delete
    /// Stop the VM without storing in-memory content. default action.
    case stop
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .delete: return 1
      case .stop: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INSTANCE_TERMINATION_ACTION_UNSPECIFIED"
      case .delete: return "DELETE"
      case .stop: return "STOP"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InstanceTerminationAction/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INSTANCE_TERMINATION_ACTION_UNSPECIFIED": self = .unspecified
      case "DELETE": self = .delete
      case "STOP": self = .stop
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InstanceTerminationAction/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .delete
      case 2: self = .stop
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("INSTANCE_TERMINATION_ACTION_UNSPECIFIED")
      case .delete: return try container.encode("DELETE")
      case .stop: return try container.encode("STOP")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `Scheduling`: `"type.googleapis.com/google.cloud.backupdr.v1.Scheduling"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.Scheduling"
  }

  /// Initialize an instance of `Scheduling` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.backupdr.v1.Scheduling"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Scheduling` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
