// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// `StandardSchedule` defines a schedule that run within the confines of a
/// defined window of days. We can define recurrence type for schedule as
/// HOURLY, DAILY, WEEKLY, MONTHLY or YEARLY.
public struct StandardSchedule: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Specifies the `RecurrenceType` for the schedule.
  public var recurrenceType: StandardSchedule.RecurrenceType = StandardSchedule.RecurrenceType()

  /// Optional. Specifies frequency for hourly backups. A hourly frequency of 2
  /// means jobs will run every 2 hours from start time till end time defined.
  ///
  /// This is required for `recurrence_type`, `HOURLY` and is not applicable
  /// otherwise. A validation error will occur if a value is supplied and
  /// `recurrence_type` is not `HOURLY`.
  ///
  /// Value of hourly frequency should be between 4 and 23.
  ///
  /// Reason for limit : We found that there is bandwidth limitation of 3GB/S for
  /// GMI while taking a backup and 5GB/S while doing a restore. Given the amount
  /// of parallel backups and restore we are targeting, this will potentially
  /// take the backup time to mins and hours (in worst case scenario).
  public var hourlyFrequency: Swift.Int32 = Swift.Int32()

  /// Optional. Specifies days of week like, MONDAY or TUESDAY, on which jobs
  /// will run.
  ///
  /// This is required for `recurrence_type`, `WEEKLY` and is not applicable
  /// otherwise. A validation error will occur if a value is supplied and
  /// `recurrence_type` is not `WEEKLY`.
  public var daysOfWeek: [GoogleType.DayOfWeek] = []

  /// Optional. Specifies days of months like 1, 5, or 14 on which jobs will run.
  ///
  /// Values for `days_of_month` are only applicable for `recurrence_type`,
  /// `MONTHLY` and `YEARLY`. A validation error will occur if other values are
  /// supplied.
  public var daysOfMonth: [Swift.Int32] = []

  /// Optional. Specifies a week day of the month like, FIRST SUNDAY or LAST
  /// MONDAY, on which jobs will run. This will be specified by two fields in
  /// `WeekDayOfMonth`, one for the day, e.g. `MONDAY`, and one for the week,
  /// e.g. `LAST`.
  ///
  /// This field is only applicable for `recurrence_type`, `MONTHLY` and
  /// `YEARLY`. A validation error will occur if other values are supplied.
  public var weekDayOfMonth: WeekDayOfMonth? = nil

  /// Optional. Specifies the months of year, like `FEBRUARY` and/or `MAY`, on
  /// which jobs will run.
  ///
  /// This field is only applicable when `recurrence_type` is `YEARLY`. A
  /// validation error will occur if other values are supplied.
  public var months: [GoogleType.Month] = []

  /// Required. A BackupWindow defines the window of day during which backup jobs
  /// will run. Jobs are queued at the beginning of the window and will be marked
  /// as `NOT_RUN` if they do not start by the end of the window.
  ///
  /// Note: running jobs will not be cancelled at the end of the window.
  public var backupWindow: BackupWindow? = nil

  /// Required. The time zone to be used when interpreting the schedule.
  /// The value of this field must be a time zone name from the IANA tz database.
  /// See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the
  /// list of valid timezone names. For e.g., Europe/Paris.
  public var timeZone: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StandardSchedule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StandardSchedule().with { $0.recurrenceType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let recurrenceType = CodingKeys(stringValue: "recurrenceType")
    static let hourlyFrequency = CodingKeys(stringValue: "hourlyFrequency")
    static let daysOfWeek = CodingKeys(stringValue: "daysOfWeek")
    static let daysOfMonth = CodingKeys(stringValue: "daysOfMonth")
    static let weekDayOfMonth = CodingKeys(stringValue: "weekDayOfMonth")
    static let months = CodingKeys(stringValue: "months")
    static let backupWindow = CodingKeys(stringValue: "backupWindow")
    static let timeZone = CodingKeys(stringValue: "timeZone")

    static let _knownKeys: Set<Swift.String> = [
      "recurrenceType",
      "hourlyFrequency",
      "daysOfWeek",
      "daysOfMonth",
      "weekDayOfMonth",
      "months",
      "backupWindow",
      "timeZone",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      StandardSchedule.RecurrenceType.self, forKey: .recurrenceType)
    {
      self.recurrenceType = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .hourlyFrequency) {
      self.hourlyFrequency = value
    }
    if let value = try container.decodeIfPresent([GoogleType.DayOfWeek].self, forKey: .daysOfWeek) {
      self.daysOfWeek = value
    }
    if let value = try container.decodeIfPresent([Swift.Int32].self, forKey: .daysOfMonth) {
      self.daysOfMonth = value
    }
    self.weekDayOfMonth = try container.decodeIfPresent(
      WeekDayOfMonth.self, forKey: .weekDayOfMonth)
    if let value = try container.decodeIfPresent([GoogleType.Month].self, forKey: .months) {
      self.months = value
    }
    self.backupWindow = try container.decodeIfPresent(BackupWindow.self, forKey: .backupWindow)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .timeZone) {
      self.timeZone = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.recurrenceType, forKey: .recurrenceType)
    try container.encode(self.hourlyFrequency, forKey: .hourlyFrequency)
    try container.encode(self.daysOfWeek, forKey: .daysOfWeek)
    try container.encode(self.daysOfMonth, forKey: .daysOfMonth)
    try container.encodeIfPresent(self.weekDayOfMonth, forKey: .weekDayOfMonth)
    try container.encode(self.months, forKey: .months)
    try container.encodeIfPresent(self.backupWindow, forKey: .backupWindow)
    try container.encode(self.timeZone, forKey: .timeZone)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// `RecurrenceTypes` enumerates the applicable periodicity for the schedule.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum RecurrenceType: Codable, Equatable, Hashable, Sendable {
    /// recurrence type not set
    case unspecified
    /// The `BackupRule` is to be applied hourly.
    case hourly
    /// The `BackupRule` is to be applied daily.
    case daily
    /// The `BackupRule` is to be applied weekly.
    case weekly
    /// The `BackupRule` is to be applied monthly.
    case monthly
    /// The `BackupRule` is to be applied yearly.
    case yearly
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .hourly: return 1
      case .daily: return 2
      case .weekly: return 3
      case .monthly: return 4
      case .yearly: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RECURRENCE_TYPE_UNSPECIFIED"
      case .hourly: return "HOURLY"
      case .daily: return "DAILY"
      case .weekly: return "WEEKLY"
      case .monthly: return "MONTHLY"
      case .yearly: return "YEARLY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RecurrenceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RECURRENCE_TYPE_UNSPECIFIED": self = .unspecified
      case "HOURLY": self = .hourly
      case "DAILY": self = .daily
      case "WEEKLY": self = .weekly
      case "MONTHLY": self = .monthly
      case "YEARLY": self = .yearly
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RecurrenceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .hourly
      case 2: self = .daily
      case 3: self = .weekly
      case 4: self = .monthly
      case 5: self = .yearly
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("RECURRENCE_TYPE_UNSPECIFIED")
      case .hourly: return try container.encode("HOURLY")
      case .daily: return try container.encode("DAILY")
      case .weekly: return try container.encode("WEEKLY")
      case .monthly: return try container.encode("MONTHLY")
      case .yearly: return try container.encode("YEARLY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.StandardSchedule"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
