// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ManagementURI depending on the Workforce Identity i.e. either 1p or 3p.
public struct WorkforceIdentityBasedManagementURI: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. First party Management URI for Google Identities.
  public var firstPartyManagementUri: Swift.String = Swift.String()

  /// Output only. Third party Management URI for External Identity Providers.
  public var thirdPartyManagementUri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `WorkforceIdentityBasedManagementURI`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WorkforceIdentityBasedManagementURI().with { $0.firstPartyManagementUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let firstPartyManagementUri = CodingKeys(stringValue: "firstPartyManagementUri")
    static let thirdPartyManagementUri = CodingKeys(stringValue: "thirdPartyManagementUri")

    static let _knownKeys: Set<Swift.String> = [
      "firstPartyManagementUri",
      "thirdPartyManagementUri",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .firstPartyManagementUri)
    {
      self.firstPartyManagementUri = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .thirdPartyManagementUri)
    {
      self.thirdPartyManagementUri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.firstPartyManagementUri, forKey: .firstPartyManagementUri)
    try container.encode(self.thirdPartyManagementUri, forKey: .thirdPartyManagementUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.backupdr.v1.WorkforceIdentityBasedManagementURI"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
